// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 263–295, <sc-if value="{{ scr.activity }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrActivityTpl({ v }: { v: any }) {
  return (
    <>
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(16px, 2cqi, 24px)", display: "flex", flexDirection: "column", gap: "10px" }}>
      <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Next · 10:30</span>
      <span style={{ fontSize: "clamp(22px, 2.3cqi, 28px)", fontWeight: "500", letterSpacing: "-0.4px", color: "#5E4E3B" }}>Keroncong sing-along</span>
      <span style={{ fontSize: "15px", lineHeight: "1.5", color: "#24201C" }}>Music room · with Dinar · 3 members in the club. Photos are tagged by face and reach each family's Today page.</span>
      <div style={{ display: "flex", gap: "8px", marginTop: "4px", flexWrap: "wrap" }}>
        <button onclick={v.goCamera} style={{ height: "44px", padding: "0 18px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "15px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "7px", cursor: "pointer", fontFamily: "Inter" }}>
          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>photo_camera</span>
          Camera
        </button>
        <button onclick={v.goLog} style={{ height: "44px", padding: "0 18px", borderRadius: "999px", border: "1px solid #D9CCBC", background: "#FFFFFF", color: "#2B231C", fontSize: "15px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "7px", cursor: "pointer", fontFamily: "Inter" }}>
          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>edit_note</span>
          Daily log
        </button>
      </div>
    </section>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(12px, 2cqi, 24px)", alignItems: "flex-start" }}>
      <section style={{ flex: "1 1 420px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "14px 18px 10px", display: "flex", justifyContent: "space-between" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>In the club</span>
          <span style={{ fontSize: "14px", color: "#5E5852" }}>3 · 0 logged</span>
        </div>
        {(v.act.members || []).map((m: any, m_i: number) => (
          <Fragment key={m_i}>
            <div style={{ display: "flex", gap: "12px", alignItems: "center", padding: "10px 18px", borderTop: "1px solid #F0EAE1", minHeight: "64px" }}>
              <span style={{ width: "40px", height: "40px", borderRadius: "999px", background: m.avBg, color: m.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>{m.ini}</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{m.name}</span>
                <span style={{ fontSize: "13px", color: "#5E5852", lineHeight: "1.4" }}>{m.sub}</span>
              </span>
              <button onclick={v.goLog} style={{ height: "34px", padding: "0 12px", borderRadius: "999px", border: "1px solid #D9CCBC", background: "#FFFFFF", color: "#2B231C", fontSize: "13px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter", flex: "none" }}>Write log</button>
            </div>
          </Fragment>
        ))}
      </section>
      <section style={{ flex: "1 1 360px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "14px 18px 10px" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Later today</span>
        </div>
        {(v.act.later || []).map((e: any, e_i: number) => (
          <Fragment key={e_i}>
            <div style={{ display: "flex", gap: "12px", alignItems: "center", padding: "10px 18px", borderTop: "1px solid #F0EAE1", minHeight: "60px" }}>
              <span style={{ width: "38px", height: "38px", borderRadius: "999px", background: "#F3EEE8", color: "#75624B", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1" }}>{e.glyph}</span>
              </span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{e.title}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{e.sub}</span>
              </span>
              <span style={{ fontSize: "14px", fontVariantNumeric: "tabular-nums" }}>{e.time}</span>
            </div>
          </Fragment>
        ))}
      </section>
    </div>
    </>
  );
}
