// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 137–176, <sc-if value="{{ scr.arrivals }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrArrivalsTpl({ v }: { v: any }) {
  return (
    <>
    <div role="tablist" style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "clamp(8px, 2cqi, 32px)", maxWidth: "640px" }}>
      {(v.lb3.tabs || []).map((t: any, t_i: number) => (
        <Fragment key={t_i}>
          <button role="tab" onclick={t.onClick} style={{ display: "flex", flexDirection: "column", alignItems: "flex-start", gap: "4px", padding: "0 0 12px", border: "none", borderBottom: `2px solid ${t.line}`, background: "transparent", cursor: "pointer", textAlign: "left", fontFamily: "Inter", color: "#1E1A16" }}>
            <span style={{ fontSize: "clamp(32px, 3.8cqi, 44px)", lineHeight: "1", fontWeight: "300", letterSpacing: "-1px", color: t.numColor }}>{t.n}</span>
            <span style={{ fontSize: "13px", fontWeight: t.weight, color: t.labelColor }}>{t.label}</span>
          </button>
        </Fragment>
      ))}
    </div>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(24px, 4cqi, 56px)", alignItems: "flex-start" }}>
      <section style={{ flex: "1 1 440px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "28px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 18px 40px rgba(60,40,20,.07)", padding: "8px clamp(18px, 3cqi, 36px) 12px" }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px", padding: "14px 0 10px" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>{v.lb3.list.title}</span>
          <label style={{ display: "flex", alignItems: "center", gap: "6px", borderBottom: "1px solid #DDD1C2", padding: "4px 2px", width: "min(220px, 50%)" }}>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1", color: "#6B6259" }}>search</span>
            <input placeholder="Search" style={{ flex: "1", minWidth: "0", border: "none", outline: "none", background: "transparent", fontSize: "15px", fontFamily: "Inter", color: "#1E1A16" }} />
          </label>
        </div>
        {(v.lb3.rows || []).map((r: any, r_i: number) => (
          <Fragment key={r_i}>
            <div style={{ display: "flex", alignItems: "center", gap: "16px", padding: "18px 0", borderTop: "1px solid #F0EAE1" }}>
              <span style={{ width: "46px", height: "46px", borderRadius: "999px", background: r.avBg, color: r.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "15px", fontWeight: "500", flex: "none" }}>{r.ini}</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "3px" }}>
                <span style={{ fontSize: "17px", fontWeight: "500" }}>{r.name}</span>
                <span style={{ fontSize: "14px", color: "#6B6259", display: "flex", alignItems: "center", gap: "10px", flexWrap: "wrap" }}>
                  {r.sub}
                  {r.hasAllergy ? (
                    <>
                      <span style={{ color: "#A2452B", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "5px" }}>
                        <span style={{ width: "6px", height: "6px", borderRadius: "999px", background: "#A2452B" }} />
                        {r.allergy}
                      </span>
                    </>
                  ) : null}
                  {r.hasStatus ? (
                    <>
                      <span style={{ color: r.stFg, fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "5px" }}>
                        <span style={{ width: "6px", height: "6px", borderRadius: "999px", background: r.stFg }} />
                        {r.status}
                      </span>
                    </>
                  ) : null}
                </span>
              </span>
              <button onclick={r.onBtn} style={{ height: "40px", padding: "0 18px", borderRadius: "999px", border: `1px solid ${r.btnBd}`, background: r.btnBg, color: r.btnFg, fontSize: "14px", fontWeight: "500", cursor: "pointer", flex: "none", fontFamily: "Inter" }}>{r.btn}</button>
            </div>
          </Fragment>
        ))}
        {v.lb3.empty ? (
          <>
            <div style={{ padding: "28px 0", borderTop: "1px solid #F0EAE1", fontSize: "20px", fontWeight: "300", color: "#6B6259" }}>{v.lb3.list.empty}</div>
          </>
        ) : null}
      </section>
      <aside style={{ flex: "0 1 300px", width: "100%", minWidth: "0", display: "flex", flexDirection: "column", gap: "18px", paddingTop: "8px" }}>
        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Also today</span>
        <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
          <span style={{ fontSize: "19px", lineHeight: "1.3", fontWeight: "500", color: "#2B231C" }}>Trial day for Oma Siu Lan Tjandra</span>
          <span style={{ fontSize: "14px", color: "#6B6259" }}>10:30 · with Melinda, her daughter</span>
          <a href="#" style={{ fontSize: "14px", marginTop: "4px" }}>Check her in</a>
        </div>
        <div style={{ height: "1px", background: "#E6DDD1" }} />
        <a href="#" onclick={v.goChat} style={{ fontSize: "14px", color: "#1E1A16", textDecoration: "none", display: "flex", alignItems: "center", gap: "8px" }}>
          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1", color: "#6E5A43", fontVariationSettings: "'wght' 300" }}>chat</span>
          2 unread messages from families
          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1", color: "#6E5A43" }}>arrow_forward</span>
        </a>
        <a href="#" onclick={v.lb3.simulate} style={{ fontSize: "14px", color: "#1E1A16", textDecoration: "none", display: "flex", alignItems: "center", gap: "8px" }}>
          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1", color: "#6E5A43", fontVariationSettings: "'wght' 300" }}>photo_camera_front</span>
          {v.lb3.camText}
        </a>
      </aside>
    </div>
    </>
  );
}
