// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 900–934, <sc-if value="{{ scr.bc }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrBcTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(12px, 2cqi, 24px)", alignItems: "flex-start" }}>
      <section style={{ flex: "1 1 480px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(14px, 1.8cqi, 20px)", display: "flex", flexDirection: "column", gap: "14px" }}>
        {(v.bcv.groups || []).map((g: any, g_i: number) => (
          <Fragment key={g_i}>
            <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
              <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>{g.label}</span>
              <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                {(g.opts || []).map((o: any, o_i: number) => (
                  <Fragment key={o_i}>
                    <button onclick={o.onClick} style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: o.bd, background: o.bg, color: o.fg, fontSize: "14px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", fontFamily: "Inter" }}>{o.label}</button>
                  </Fragment>
                ))}
              </div>
            </div>
          </Fragment>
        ))}
        <label style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Message</span>
          <textarea rows="3" value={v.bcv.msg} onchange={v.bcv.onMsg} placeholder="Our new garden room opens on Monday." style={{ border: "1px solid #DDD1C2", borderRadius: "14px", padding: "12px 14px", fontSize: "16px", lineHeight: "22px", fontFamily: "Inter", color: "#24201C", outline: "none", resize: "vertical" }} />
        </label>
        <button onclick={v.bcv.send} style={{ height: "48px", borderRadius: "999px", border: "none", background: v.bcv.sendBg, color: v.bcv.sendFg, fontSize: "15px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>{v.bcv.sendLabel}</button>
      </section>
      <div style={{ flex: "0 1 340px", width: "100%", minWidth: "0", display: "flex", flexDirection: "column", gap: "8px" }}>
        <span style={{ fontSize: "13px", color: "#5E5852" }}>Preview for Cynthia Gunawan · “{v.bcv.tpl}”</span>
        <div style={{ borderRadius: "20px", background: "#E6DDD1", padding: "14px" }}>
          <div style={{ background: "#FFFFFF", borderRadius: "14px", padding: "12px 14px", display: "flex", flexDirection: "column", gap: "6px" }}>
            <span style={{ fontSize: "12px", fontWeight: "600", color: "#3D6B4F" }}>CitraPremier</span>
            <span style={{ fontSize: "15px", lineHeight: "1.45" }}>{v.bcv.preview}</span>
            <span style={{ alignSelf: "flex-end", fontSize: "11px", color: "#5E5852" }}>09:58</span>
            <span style={{ borderTop: "1px solid #F0EAE1", paddingTop: "8px", textAlign: "center", fontSize: "14px", color: "#75624B", fontWeight: "500" }}>Open the CitraPremier app</span>
          </div>
        </div>
        <span style={{ fontSize: "12px", color: "#5E5852" }}>Demo: WhatsApp messages are simulated.</span>
      </div>
    </div>
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
      <div style={{ padding: "14px 18px 10px", fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Sent and scheduled</div>
      {(v.bcv.sent || []).map((s: any, s_i: number) => (
        <Fragment key={s_i}>
          <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "12px 18px", borderTop: "1px solid #F0EAE1" }}>
            <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
              <span style={{ fontSize: "15px", fontWeight: "500" }}>{s.title}</span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{s.sub}</span>
            </span>
            <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: "#E3EFE6", color: "#2F5A40", fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>check_circle</span>
              Sent
            </span>
          </div>
        </Fragment>
      ))}
    </section>
    </>
  );
}
