// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 802–833, <sc-if value="{{ scr.budget }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrBudgetTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
      <button aria-label="Previous week" style={{ width: "40px", height: "40px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" }}>
        <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>chevron_left</span>
      </button>
      <span style={{ fontSize: "15px", fontWeight: "600", padding: "0 6px" }}>Mon 19 Oct – Sun 25 Oct</span>
      <button aria-label="Next week" style={{ width: "40px", height: "40px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" }}>
        <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>chevron_right</span>
      </button>
    </div>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "clamp(10px, 1.5cqi, 16px)" }}>
      {(v.bg.sections || []).map((b: any, b_i: number) => (
        <Fragment key={b_i}>
          <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "16px 18px", display: "flex", flexDirection: "column", gap: "10px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
              <span style={{ flex: "1", fontSize: "20px", fontWeight: "400", color: "#2B231C" }}>{b.name}</span>
              {b.hasWaiting ? (
                <>
                  <span style={{ height: "22px", padding: "0 8px", borderRadius: "999px", background: "#F6ECD6", color: "#7A5510", fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center" }}>1 waiting</span>
                </>
              ) : null}
              <button aria-label="Edit" style={{ width: "32px", height: "32px", borderRadius: "999px", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#5E5852" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1" }}>edit</span>
              </button>
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>Weekly budget</span>
              <span style={{ fontSize: "18px", fontWeight: "500", fontVariantNumeric: "tabular-nums" }}>{b.budget}</span>
            </div>
            <div style={{ height: "8px", borderRadius: "999px", background: "#F0EAE1", overflow: "hidden", display: "flex" }}>
              <span style={{ width: `${b.pct}%`, background: "#75624B" }} />
              <span style={{ width: `${b.cpct}%`, background: "#CAB8A2" }} />
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: "13px" }}>
              <span>{b.spent}</span>
              <span style={{ color: "#2F5A40", fontWeight: "600" }}>{b.left}</span>
            </div>
            {(b.items || []).map((i: any, i_i: number) => (
              <Fragment key={i_i}>
                <div style={{ borderTop: "1px solid #F0EAE1", paddingTop: "10px", display: "flex", flexDirection: "column", gap: "8px" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", gap: "8px", alignItems: "flex-start" }}>
                    <span style={{ display: "flex", flexDirection: "column", gap: "1px" }}>
                      <span style={{ fontSize: "14px", fontWeight: "500" }}>{i.title}</span>
                      <span style={{ fontSize: "12px", color: "#5E5852" }}>{i.sub}</span>
                    </span>
                    <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: i.sBg, color: i.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", flex: "none" }}>
                      <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{i.sIcon}</span>
                      {i.sText}
                    </span>
                  </div>
                  {i.waiting ? (
                    <>
                      <div style={{ display: "flex", gap: "8px" }}>
                        <button onclick={i.approve} style={{ height: "36px", padding: "0 16px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "13px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>Approve</button>
                        <button onclick={i.reject} style={{ height: "36px", padding: "0 14px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", color: "#9A3D24", fontSize: "13px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter" }}>Reject</button>
                      </div>
                    </>
                  ) : null}
                </div>
              </Fragment>
            ))}
          </section>
        </Fragment>
      ))}
    </div>
    <section style={{ maxWidth: "900px", width: "100%", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "16px 18px", display: "flex", flexDirection: "column", gap: "10px" }}>
      <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Request from a section</span>
      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
        <select style={{ flex: "0 1 150px", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 10px", fontSize: "15px", fontFamily: "Inter", background: "#FFFFFF", color: "#24201C" }}>
          <option>{"F&B"}</option>
          <option>Activities</option>
          <option>Operations</option>
        </select>
        <input placeholder="What is it for?" style={{ flex: "2 1 200px", minWidth: "0", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", outline: "none" }} />
        <label style={{ flex: "1 1 150px", display: "flex", alignItems: "center", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", overflow: "hidden" }}>
          <span style={{ padding: "0 12px", height: "100%", display: "flex", alignItems: "center", background: "#F6F1EA", borderRight: "1px solid #DCD3C8", fontSize: "15px" }}>Rp</span>
          <input inputmode="numeric" placeholder="Amount" style={{ flex: "1", minWidth: "0", height: "100%", border: "none", outline: "none", padding: "0 12px", fontSize: "16px", fontFamily: "Inter" }} />
        </label>
        <button style={{ height: "44px", padding: "0 18px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "14px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>Send request</button>
      </div>
    </section>
    </>
  );
}
