// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 667–703, <sc-if value="{{ scr.cal }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrCalTpl({ v }: { v: any }) {
  return (
    <>
    <div role="tablist" style={{ display: "flex", gap: "4px", padding: "4px", borderRadius: "999px", background: "#EDE5DA", alignSelf: "flex-start" }}>
      {(v.cal.tabs || []).map((t: any, t_i: number) => (
        <Fragment key={t_i}>
          <button role="tab" onclick={t.onClick} style={{ height: "38px", padding: "0 16px", borderRadius: "999px", border: "none", background: t.bg, boxShadow: t.shadow, color: "#24201C", fontSize: "14px", fontWeight: t.weight, display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>{t.icon}</span>
            {t.label}
          </button>
        </Fragment>
      ))}
    </div>
    {v.cal.isList ? (
      <>
        {(v.cal.days || []).map((d: any, d_i: number) => (
          <Fragment key={d_i}>
            <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
              <div style={{ padding: "12px 18px", display: "flex", alignItems: "center", gap: "10px", flexWrap: "wrap", background: "#FBFAF8", borderBottom: "1px solid #F0EAE1" }}>
                <span style={{ flex: "1", fontSize: "16px", fontWeight: "600" }}>{d.title}</span>
                {d.today ? (
                  <>
                    <span style={{ height: "22px", padding: "0 8px", borderRadius: "999px", background: "#2B231C", color: "#FFFFFF", fontSize: "11px", fontWeight: "700", letterSpacing: "1px", display: "inline-flex", alignItems: "center" }}>TODAY</span>
                  </>
                ) : null}
                <span style={{ fontSize: "13px", color: "#2F5A40", fontWeight: "600" }}>Open · 08:30–16:30</span>
              </div>
              {(d.events || []).map((e: any, e_i: number) => (
                <Fragment key={e_i}>
                  <div style={{ display: "flex", alignItems: "center", gap: "14px", padding: "10px 18px", borderTop: "1px solid #F0EAE1", minHeight: "58px" }}>
                    <span style={{ width: "46px", fontSize: "14px", fontWeight: "500", fontVariantNumeric: "tabular-nums", flex: "none" }}>{e.time}</span>
                    <span style={{ width: "36px", height: "36px", borderRadius: "999px", background: e.bg, color: e.fg, display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}>
                      <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>{e.icon}</span>
                    </span>
                    <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                      <span style={{ fontSize: "15px", fontWeight: "500" }}>{e.title}</span>
                      <span style={{ fontSize: "13px", color: "#5E5852" }}>{e.sub}</span>
                    </span>
                  </div>
                </Fragment>
              ))}
            </section>
          </Fragment>
        ))}
      </>
    ) : null}
    {v.cal.isMonth ? (
      <>
        <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(12px, 1.8cqi, 20px)", display: "flex", flexDirection: "column", gap: "10px" }}>
          <span style={{ fontSize: "18px", fontWeight: "400", color: "#2B231C" }}>October 2026</span>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(7, minmax(0, 1fr))", gap: "6px" }}>
            {(v.cal.dow || []).map((w: any, w_i: number) => (
              <Fragment key={w_i}>
                <span style={{ fontSize: "12px", fontWeight: "600", color: "#5E5852", textAlign: "center", padding: "4px 0" }}>{w}</span>
              </Fragment>
            ))}
            {(v.cal.cells || []).map((c: any, c_i: number) => (
              <Fragment key={c_i}>
                <div style={{ minHeight: "clamp(44px, 7cqi, 84px)", borderRadius: "12px", background: c.bg, border: c.bd, padding: "6px", display: "flex", flexDirection: "column", gap: "4px", opacity: c.op }}>
                  <span style={{ fontSize: "13px", fontWeight: c.weight, color: c.fg }}>{c.n}</span>
                  {c.has ? (
                    <>
                      <span style={{ display: "flex", gap: "3px", flexWrap: "wrap" }}>
                        {(c.dots || []).map((x: any, x_i: number) => (
                          <Fragment key={x_i}>
                            <span style={{ width: "6px", height: "6px", borderRadius: "999px", background: "#3D6B4F" }} />
                          </Fragment>
                        ))}
                      </span>
                    </>
                  ) : null}
                </div>
              </Fragment>
            ))}
          </div>
        </section>
      </>
    ) : null}
    </>
  );
}
