// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 594–632, <sc-if value="{{ scr.camera }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrCameraTpl({ v }: { v: any }) {
  return (
    <>
    <div role="tablist" style={{ display: "flex", gap: "4px", padding: "4px", borderRadius: "999px", background: "#EDE5DA", alignSelf: "flex-start" }}>
      {(v.cm.tabs || []).map((t: any, t_i: number) => (
        <Fragment key={t_i}>
          <button role="tab" onclick={t.onClick} style={{ height: "38px", padding: "0 18px", borderRadius: "999px", border: "none", background: t.bg, boxShadow: t.shadow, color: "#24201C", fontSize: "14px", fontWeight: t.weight, cursor: "pointer", fontFamily: "Inter" }}>{t.label}</button>
        </Fragment>
      ))}
    </div>
    {v.cm.isCam ? (
      <>
        <div style={{ width: "100%", maxWidth: "760px", display: "flex", flexDirection: "column", gap: "12px" }}>
          <div style={{ position: "relative", aspectRatio: "4 / 3", maxHeight: "56cqi", borderRadius: "20px", background: "#2E2924", color: "#F4F0EE", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "8px", textAlign: "center", padding: "0 32px" }}>
            <span style={{ position: "absolute", top: "16px", left: "16px", width: "28px", height: "28px", borderTop: "2px solid #CAB8A2", borderLeft: "2px solid #CAB8A2", borderTopLeftRadius: "8px" }} />
            <span style={{ position: "absolute", top: "16px", right: "16px", width: "28px", height: "28px", borderTop: "2px solid #CAB8A2", borderRight: "2px solid #CAB8A2", borderTopRightRadius: "8px" }} />
            <span style={{ position: "absolute", bottom: "16px", left: "16px", width: "28px", height: "28px", borderBottom: "2px solid #CAB8A2", borderLeft: "2px solid #CAB8A2", borderBottomLeftRadius: "8px" }} />
            <span style={{ position: "absolute", bottom: "16px", right: "16px", width: "28px", height: "28px", borderBottom: "2px solid #CAB8A2", borderRight: "2px solid #CAB8A2", borderBottomRightRadius: "8px" }} />
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "40px", lineHeight: "1", color: "#CAB8A2" }}>groups</span>
            <span style={{ fontSize: "18px", fontWeight: "500" }}>{v.cm.title}</span>
            <span style={{ fontSize: "14px", lineHeight: "1.45", color: "#E8E1D8", maxWidth: "340px" }}>{v.cm.sub}</span>
          </div>
          <div style={{ display: "flex", gap: "10px", flexWrap: "wrap" }}>
            <button onclick={v.cm.take} style={{ flex: "2 1 220px", height: "52px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "16px", fontWeight: "600", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px", cursor: "pointer", fontFamily: "Inter" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "22px", lineHeight: "1" }}>photo_camera</span>
              Take group photo
            </button>
            <button style={{ flex: "1 1 180px", height: "52px", borderRadius: "999px", border: "1px solid #D9CCBC", background: "#FFFFFF", color: "#2B231C", fontSize: "15px", fontWeight: "500", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px", cursor: "pointer", fontFamily: "Inter" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "21px", lineHeight: "1" }}>videocam</span>
              Short video
            </button>
          </div>
          <span style={{ fontSize: "13px", color: "#5E5852", display: "flex", gap: "6px", alignItems: "flex-start", lineHeight: "1.45" }}>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "17px", lineHeight: "1.2" }}>lock</span>
            Photos go straight to each tagged family's Today page. Nothing is saved to this phone's gallery.
          </span>
        </div>
      </>
    ) : null}
    {v.cm.isLib ? (
      <>
        {v.cm.noPhotos ? (
          <>
            <section style={{ background: "#FFFFFF", border: "1px solid #E4DACD", borderRadius: "20px", padding: "36px 24px", display: "flex", flexDirection: "column", alignItems: "center", gap: "8px", textAlign: "center", maxWidth: "760px" }}>
              <span style={{ width: "56px", height: "56px", borderRadius: "999px", background: "#F3EEE8", color: "#75624B", display: "flex", alignItems: "center", justifyContent: "center" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "28px", lineHeight: "1" }}>photo_library</span>
              </span>
              <span style={{ fontSize: "17px", fontWeight: "500" }}>No photos yet today</span>
              <span style={{ fontSize: "14px", color: "#5E5852" }}>Photos you take show here until management approves them.</span>
            </section>
          </>
        ) : null}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))", gap: "10px", maxWidth: "900px" }}>
          {(v.cm.photos || []).map((p: any, p_i: number) => (
            <Fragment key={p_i}>
              <div style={{ borderRadius: "16px", overflow: "hidden", background: "#FFFFFF", border: "1px solid #E4DACD" }}>
                <div style={{ aspectRatio: "4 / 3", background: p.bg }} />
                <div style={{ padding: "8px 10px", display: "flex", flexDirection: "column", gap: "2px" }}>
                  <span style={{ fontSize: "13px", fontWeight: "600" }}>{p.title}</span>
                  <span style={{ fontSize: "12px", color: "#7A5510" }}>Waiting for approval</span>
                </div>
              </div>
            </Fragment>
          ))}
        </div>
      </>
    ) : null}
    </>
  );
}
