// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 433–476, <sc-if value="{{ scr.chat }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrChatTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", gap: "clamp(12px, 2cqi, 20px)", alignItems: "stretch", height: "clamp(520px, 60cqi, 690px)" }}>
      {v.ch.showList ? (
        <>
          <section style={{ flex: "1 1 300px", maxWidth: v.ch.listMax, minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflowY: "auto" }}>
            {(v.ch.threads || []).map((t: any, t_i: number) => (
              <Fragment key={t_i}>
                <button onclick={t.onClick} style={{ width: "100%", display: "flex", gap: "12px", alignItems: "flex-start", padding: "14px 16px", border: "none", borderBottom: "1px solid #F0EAE1", borderLeft: `3px solid ${t.bar}`, background: t.bg, textAlign: "left", cursor: "pointer", fontFamily: "Inter", color: "#24201C" }}>
                  <span style={{ width: "40px", height: "40px", borderRadius: "999px", background: "#EDE5DA", color: "#5E4E3B", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>{t.ini}</span>
                  <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
                    <span style={{ display: "flex", justifyContent: "space-between", gap: "8px", alignItems: "center" }}>
                      <span style={{ fontSize: "15px", fontWeight: t.weight }}>{t.name}</span>
                      <span style={{ fontSize: "12px", color: "#5E5852", whiteSpace: "nowrap", display: "flex", alignItems: "center", gap: "6px" }}>
                        {t.time}
                        {t.unread ? (
                          <>
                            <span style={{ width: "8px", height: "8px", borderRadius: "999px", background: "#3D6B4F" }} />
                          </>
                        ) : null}
                      </span>
                    </span>
                    <span style={{ fontSize: "12px", color: "#3D6B4F", fontWeight: "600" }}>{t.about}</span>
                    <span style={{ fontSize: "14px", color: "#5E5852", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{t.last}</span>
                  </span>
                </button>
              </Fragment>
            ))}
          </section>
        </>
      ) : null}
      {v.ch.showThread ? (
        <>
          <section style={{ flex: "1 1 480px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden", display: "flex", flexDirection: "column" }}>
            <div style={{ padding: "12px 16px", display: "flex", alignItems: "center", gap: "10px", borderBottom: "1px solid #F0EAE1", flexWrap: "wrap" }}>
              {v.isPhone ? (
                <>
                  <button onclick={v.ch.back} aria-label="Back" style={{ width: "40px", height: "40px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flex: "none" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>arrow_back</span>
                  </button>
                </>
              ) : null}
              <span style={{ flex: "1 1 200px", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                <span style={{ fontSize: "16px", fontWeight: "600" }}>{v.ch.cur.name}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>
                  {v.ch.cur.rel}{" · "}
                  <a href={`tel:${v.ch.cur.phone}`}>{v.ch.cur.phone}</a>
                </span>
              </span>
              <button style={{ height: "36px", padding: "0 14px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", color: "#24201C", fontSize: "13px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter", whiteSpace: "nowrap" }}>{v.ch.cur.profile}</button>
            </div>
            <div style={{ flex: "1", minHeight: "0", overflowY: "auto", padding: "16px", display: "flex", flexDirection: "column", gap: "12px", background: "#FBFAF8" }}>
              {(v.ch.msgs || []).map((m: any, m_i: number) => (
                <Fragment key={m_i}>
                  <div style={{ display: "flex", flexDirection: "column", gap: "4px", alignItems: m.align }}>
                    <span style={{ maxWidth: "80%", padding: "10px 14px", borderRadius: "16px", background: m.bg, color: m.fg, fontSize: "15px", lineHeight: "1.45" }}>{m.text}</span>
                    <span style={{ fontSize: "12px", color: "#5E5852" }}>{m.meta}</span>
                  </div>
                </Fragment>
              ))}
            </div>
            <div style={{ padding: "10px 12px 12px", borderTop: "1px solid #F0EAE1", display: "flex", flexDirection: "column", gap: "8px" }}>
              <div style={{ display: "flex", gap: "6px", overflowX: "auto", scrollbarWidth: "none" }}>
                {(v.ch.quick || []).map((q: any, q_i: number) => (
                  <Fragment key={q_i}>
                    <button className="dh12" onclick={q.onClick} style={{ height: "34px", padding: "0 12px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", color: "#24201C", fontSize: "13px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>{q.label}</button>
                  </Fragment>
                ))}
              </div>
              <div style={{ display: "flex", gap: "8px" }}>
                <input value={v.ch.draft} onchange={v.ch.onDraft} placeholder="Write a message" style={{ flex: "1", minWidth: "0", height: "46px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", color: "#24201C", outline: "none" }} />
                <button onclick={v.ch.send} aria-label="Send" style={{ width: "46px", height: "46px", borderRadius: "999px", border: "none", background: v.ch.sendBg, color: v.ch.sendFg, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flex: "none" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "21px", lineHeight: "1" }}>send</span>
                </button>
              </div>
            </div>
          </section>
        </>
      ) : null}
    </div>
    </>
  );
}
