// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 505–523, <sc-if value="{{ scr.dir }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrDirTpl({ v }: { v: any }) {
  return (
    <>
    {v.isLaptop ? (
      <>
        <p style={{ margin: "0", fontSize: "15px", lineHeight: "1.5", maxWidth: "720px" }}>Suppliers, doctors and services. Public contacts also appear in the family app; internal ones are for staff only.</p>
      </>
    ) : null}
    <div style={{ display: "flex", gap: "8px", overflowX: "auto", scrollbarWidth: "none", flex: "none" }}>
      {(v.dir.chips || []).map((c: any, c_i: number) => (
        <Fragment key={c_i}>
          <button onclick={c.onClick} style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: c.bd, background: c.bg, color: c.fg, fontSize: "14px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>
            {c.label}{" "}
            <span style={{ opacity: ".75" }}>{c.n}</span>
          </button>
        </Fragment>
      ))}
    </div>
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden", maxWidth: "900px" }}>
      {(v.dir.rows || []).map((r: any, r_i: number) => (
        <Fragment key={r_i}>
          <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "10px clamp(14px, 1.8cqi, 20px)", minHeight: "66px", borderTop: r.bt, flexWrap: "wrap" }}>
            <span style={{ width: "38px", height: "38px", borderRadius: "999px", background: "#F3EEE8", color: "#75624B", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1" }}>{r.icon}</span>
            </span>
            <span style={{ flex: "1 1 220px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
              <span style={{ fontSize: "15px", fontWeight: "500" }}>{r.name}</span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{r.sub}</span>
            </span>
            <span style={{ display: "flex", alignItems: "center", gap: "10px", marginLeft: "auto" }}>
              <a href={`tel:${r.phone}`} style={{ fontSize: "14px", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap", display: "inline-flex", alignItems: "center", gap: "5px", textDecoration: "none" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "17px", lineHeight: "1" }}>call</span>
                {r.phone}
              </a>
              <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: r.vBg, color: r.vFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1" }}>{r.vIcon}</span>
                {r.vis}
              </span>
              <button className="dh14" aria-label="More" style={{ width: "34px", height: "34px", borderRadius: "999px", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#5E5852" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>more_vert</span>
              </button>
            </span>
          </div>
        </Fragment>
      ))}
    </section>
    </>
  );
}
