// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 635–664, <sc-if value="{{ scr.dlog }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrDlogTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", gap: "8px", overflowX: "auto", scrollbarWidth: "none", flex: "none", maxWidth: "760px" }}>
      {(v.dl.days || []).map((c: any, c_i: number) => (
        <Fragment key={c_i}>
          <button onclick={c.onClick} style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: c.bd, background: c.bg, color: c.fg, fontSize: "14px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>{c.label}</button>
        </Fragment>
      ))}
    </div>
    <div style={{ maxWidth: "760px", width: "100%", display: "flex", flexDirection: "column", gap: "10px" }}>
      <span style={{ fontSize: "14px", color: "#5E5852", lineHeight: "1.45" }}>Everyone starts as Normal. Tap only what was different today. Families see the log on their Today page.</span>
      {(v.dl.rows || []).map((r: any, r_i: number) => (
        <Fragment key={r_i}>
          <section style={{ background: "#FFFFFF", border: `1px solid ${r.bd}`, borderRadius: "18px", boxShadow: "0 2px 8px rgba(60,45,30,.06)", overflow: "hidden" }}>
            <button onclick={r.toggle} style={{ width: "100%", display: "flex", gap: "12px", alignItems: "center", padding: "12px 16px", border: "none", background: "#FFFFFF", textAlign: "left", cursor: "pointer", fontFamily: "Inter", color: "#24201C" }}>
              <span style={{ width: "40px", height: "40px", borderRadius: "999px", background: r.avBg, color: r.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>{r.ini}</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{r.name}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{r.summary}</span>
              </span>
              <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: r.sBg, color: r.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", flex: "none" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1" }}>{r.sIcon}</span>
                {r.sText}
              </span>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "22px", lineHeight: "1", color: "#5E5852" }}>{r.chev}</span>
            </button>
            {r.open ? (
              <>
                <div style={{ padding: "4px 16px 16px", display: "flex", flexDirection: "column", gap: "12px", borderTop: "1px solid #F0EAE1" }}>
                  {(r.fields || []).map((f: any, f_i: number) => (
                    <Fragment key={f_i}>
                      <div style={{ display: "flex", flexDirection: "column", gap: "6px", paddingTop: "10px" }}>
                        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>{f.label}</span>
                        <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                          {(f.opts || []).map((o: any, o_i: number) => (
                            <Fragment key={o_i}>
                              <button onclick={o.onClick} style={{ height: "36px", padding: "0 12px", borderRadius: "999px", border: o.bd, background: o.bg, color: o.fg, fontSize: "13px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter" }}>{o.label}</button>
                            </Fragment>
                          ))}
                        </div>
                      </div>
                    </Fragment>
                  ))}
                  <input placeholder="Short note for the family (optional)" style={{ height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", color: "#24201C", outline: "none" }} />
                  <button onclick={r.save} style={{ alignSelf: "flex-start", height: "40px", padding: "0 18px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "14px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>Save log</button>
                </div>
              </>
            ) : null}
          </section>
        </Fragment>
      ))}
      <button onclick={v.dl.saveAll} style={{ height: "46px", borderRadius: "999px", border: "1px solid #D9CCBC", background: "#FFFFFF", color: "#2B231C", fontSize: "15px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter" }}>{v.dl.saveAllLabel}</button>
    </div>
    </>
  );
}
