// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 479–502, <sc-if value="{{ scr.enq }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrEnqTpl({ v }: { v: any }) {
  return (
    <>
    {v.isLaptop ? (
      <>
        <p style={{ margin: "0", fontSize: "15px", lineHeight: "1.5", maxWidth: "720px" }}>Trials are booked at least one day ahead. Joining copies everything into a new member record.</p>
      </>
    ) : null}
    {v.isPhone ? (
      <>
        <div style={{ display: "flex", gap: "8px", overflowX: "auto", scrollbarWidth: "none", flex: "none" }}>
          {(v.enq.cols || []).map((c: any, c_i: number) => (
            <Fragment key={c_i}>
              <button onclick={c.onPick} style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: c.bd, background: c.bg, color: c.fg, fontSize: "14px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>
                {c.title}{" "}
                <span style={{ opacity: ".75" }}>{c.n}</span>
              </button>
            </Fragment>
          ))}
        </div>
      </>
    ) : null}
    <div style={{ display: "flex", gap: "14px", overflowX: "auto", alignItems: "flex-start", paddingBottom: "6px" }}>
      {(v.enq.shown || []).map((c: any, c_i: number) => (
        <Fragment key={c_i}>
          <div style={{ flex: `1 0 ${v.enq.colW}`, minWidth: "0", background: "#F0EAE1", borderRadius: "20px", padding: "10px", display: "flex", flexDirection: "column", gap: "10px" }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "4px 6px 0" }}>
              <span style={{ fontSize: "12px", letterSpacing: "1.4px", textTransform: "uppercase", fontWeight: "600", color: c.color }}>{c.title}</span>
              <span style={{ minWidth: "24px", height: "24px", padding: "0 7px", borderRadius: "999px", background: "#FFFFFF", fontSize: "12px", fontWeight: "600", display: "flex", alignItems: "center", justifyContent: "center" }}>{c.n}</span>
            </div>
            {(c.cards || []).map((e: any, e_i: number) => (
              <Fragment key={e_i}>
                <div style={{ background: "#FFFFFF", border: "1px solid #E4DACD", borderRadius: "16px", padding: "12px", display: "flex", flexDirection: "column", gap: "8px", boxShadow: "0 1px 3px rgba(60,45,30,.05)" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", gap: "8px" }}>
                    <span style={{ display: "flex", flexDirection: "column", gap: "1px", minWidth: "0" }}>
                      <span style={{ fontSize: "15px", fontWeight: "600" }}>{e.name}</span>
                      <span style={{ fontSize: "13px", color: "#5E5852" }}>{e.contact}{" · "}{e.source}</span>
                    </span>
                    <button aria-label="More" style={{ width: "32px", height: "32px", borderRadius: "999px", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flex: "none", color: "#5E5852" }}>
                      <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>more_horiz</span>
                    </button>
                  </div>
                  <span style={{ fontSize: "13px", display: "flex", alignItems: "center", gap: "6px" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "17px", lineHeight: "1", color: "#75624B" }}>{e.nextIcon}</span>
                    {e.next}
                  </span>
                  {e.hasTag ? (
                    <>
                      <span style={{ alignSelf: "flex-start", height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: e.tBg, color: e.tFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "4px" }}>
                        <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1" }}>{e.tIcon}</span>
                        {e.tag}
                      </span>
                    </>
                  ) : null}
                  {e.hasBtn ? (
                    <>
                      <button onclick={e.onBtn} style={{ height: "36px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "13px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>{e.btn}</button>
                    </>
                  ) : null}
                </div>
              </Fragment>
            ))}
            {c.empty ? (
              <>
                <div style={{ border: "1px dashed #CAB8A2", borderRadius: "14px", padding: "16px", textAlign: "center", fontSize: "13px", color: "#5E5852" }}>No leads here</div>
              </>
            ) : null}
          </div>
        </Fragment>
      ))}
    </div>
    </>
  );
}
