// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 337–376, <sc-if value="{{ scr.finance }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrFinanceTpl({ v }: { v: any }) {
  return (
    <>
    {v.isLaptop ? (
      <>
        <p style={{ margin: "0", fontSize: "15px", lineHeight: "1.5", maxWidth: "720px", color: "#24201C" }}>Families pay by DOKU virtual account and payments sync to Xero on their own. Anything still open after its due date moves to Overdue, with call notes and reminders.</p>
      </>
    ) : null}
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "clamp(8px, 1.2cqi, 14px)" }}>
      {(v.fin.tiles || []).map((t: any, t_i: number) => (
        <Fragment key={t_i}>
          <div style={{ background: "#FFFFFF", border: "1px solid #E4DACD", borderTop: `3px solid ${t.bar}`, borderRadius: "16px", padding: "12px 14px", display: "flex", flexDirection: "column", gap: "4px", boxShadow: "0 2px 8px rgba(60,45,30,.06)" }}>
            <span style={{ fontSize: "13px", fontWeight: "500", color: "#5E5852" }}>{t.label}</span>
            <span style={{ fontSize: "clamp(24px, 2.6cqi, 32px)", fontWeight: "300", lineHeight: "1.1", letterSpacing: "-0.5px", fontVariantNumeric: "tabular-nums" }}>{t.n}</span>
            <span style={{ fontSize: "13px", fontWeight: "600", color: t.fg, fontVariantNumeric: "tabular-nums" }}>{t.amount}</span>
          </div>
        </Fragment>
      ))}
    </div>
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(14px, 1.8cqi, 20px)", display: "flex", alignItems: "center", gap: "12px 16px", flexWrap: "wrap" }}>
      <div style={{ flex: "1 1 300px", minWidth: "0", display: "flex", flexDirection: "column", gap: "3px" }}>
        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Invoice run</span>
        <span style={{ fontSize: "19px", fontWeight: "500" }}>Next run · November 2026</span>
        <span style={{ fontSize: "13px", color: "#5E5852", lineHeight: "1.4" }}>5 invoices · Rp 39.500.000 · due 27 November 2026 · last run: October, 5 invoices</span>
      </div>
      <button style={{ height: "44px", padding: "0 18px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "15px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "7px", cursor: "pointer", fontFamily: "Inter" }}>
        <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1" }}>event_repeat</span>
        Preview and issue
      </button>
    </section>
    <label style={{ height: "46px", maxWidth: "520px", display: "flex", alignItems: "center", gap: "10px", padding: "0 14px", border: "1px solid #DDD1C2", borderRadius: "14px", background: "#FFFFFF" }}>
      <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "21px", lineHeight: "1", color: "#5E5852" }}>search</span>
      <input placeholder="Search by member, invoice or family" style={{ flex: "1", minWidth: "0", border: "none", outline: "none", fontSize: "16px", fontFamily: "Inter", color: "#24201C", background: "transparent" }} />
    </label>
    {(v.fin.groups || []).map((g: any, g_i: number) => (
      <Fragment key={g_i}>
        <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
          <div style={{ padding: "14px 18px 10px", display: "flex", justifyContent: "space-between", gap: "8px", flexWrap: "wrap" }}>
            <span style={{ fontSize: "12px", letterSpacing: "1.4px", textTransform: "uppercase", fontWeight: "600", color: g.color }}>{g.title}</span>
            <span style={{ fontSize: "13px", color: "#5E5852" }}>{g.meta}</span>
          </div>
          {(g.rows || []).map((r: any, r_i: number) => (
            <Fragment key={r_i}>
              <div style={{ display: "flex", gap: "12px", alignItems: "center", padding: "10px 18px", borderTop: "1px solid #F0EAE1", minHeight: "64px", flexWrap: "wrap" }}>
                <span style={{ width: "40px", height: "40px", borderRadius: "999px", background: r.avBg, color: r.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>{r.ini}</span>
                <span style={{ flex: "1 1 220px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
                  <span style={{ fontSize: "15px", fontWeight: "500" }}>{r.name}</span>
                  <span style={{ fontSize: "13px", color: "#5E5852", lineHeight: "1.4" }}>{r.sub}</span>
                </span>
                <span style={{ display: "flex", alignItems: "center", gap: "10px", marginLeft: "auto" }}>
                  <span style={{ fontSize: "15px", fontWeight: "500", fontVariantNumeric: "tabular-nums" }}>{r.amount}</span>
                  <span style={{ height: "24px", padding: "0 9px 0 6px", borderRadius: "999px", background: r.bBg, color: r.bFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "4px", whiteSpace: "nowrap" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "15px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{r.bIcon}</span>
                    {r.bText}
                  </span>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "22px", lineHeight: "1", color: "#5E5852" }}>expand_more</span>
                </span>
              </div>
            </Fragment>
          ))}
        </section>
      </Fragment>
    ))}
    </>
  );
}
