// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 1094–1120, <sc-if value="{{ scr.fbill }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrFbillTpl({ v }: { v: any }) {
  return (
    <>
    <section style={{ background: "#FFFFFF", border: `2px solid ${v.fbl.totalBd}`, borderRadius: "20px", padding: "14px 18px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: "10px" }}>
      <span style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Total to pay</span>
        <span style={{ fontSize: "14px", color: "#5E5852" }}>{v.fbl.openText}</span>
      </span>
      <span style={{ fontSize: "26px", fontWeight: "400", letterSpacing: "-0.5px", fontVariantNumeric: "tabular-nums" }}>{v.fbl.total}</span>
    </section>
    {(v.fbl.cards || []).map((c: any, c_i: number) => (
      <Fragment key={c_i}>
        <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "16px 18px", display: "flex", flexDirection: "column", gap: "12px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
            <span style={{ width: "44px", height: "44px", borderRadius: "999px", background: c.avBg, color: c.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px", fontWeight: "500", flex: "none" }}>{c.ini}</span>
            <span style={{ flex: "1", display: "flex", flexDirection: "column", gap: "1px" }}>
              <span style={{ fontSize: "16px", fontWeight: "500" }}>{c.name}</span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{c.plan}</span>
            </span>
            <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: c.sBg, color: c.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{c.sIcon}</span>
              {c.sText}
            </span>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
            <span style={{ fontSize: "12px", letterSpacing: "1.4px", textTransform: "uppercase", fontWeight: "600", color: "#5E5852" }}>October 2026</span>
            <span style={{ fontSize: "26px", fontWeight: "400", letterSpacing: "-0.5px" }}>{c.amount}</span>
            <span style={{ fontSize: "13px", color: "#5E5852" }}>{c.inv}</span>
          </div>
          {c.open ? (
            <>
              <button onclick={c.pay} style={{ height: "46px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "15px", fontWeight: "600", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px", cursor: "pointer", fontFamily: "Inter" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>account_balance</span>
                Pay by virtual account
              </button>
            </>
          ) : null}
        </section>
      </Fragment>
    ))}
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
      <div style={{ padding: "14px 18px 10px", fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>History</div>
      {(v.fbl.history || []).map((h: any, h_i: number) => (
        <Fragment key={h_i}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "10px 18px", borderTop: "1px solid #F0EAE1", flexWrap: "wrap" }}>
            <span style={{ flex: "1 1 200px", display: "flex", flexDirection: "column", gap: "1px" }}>
              <span style={{ fontSize: "15px", fontWeight: "500" }}>{h.title}</span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{h.sub}</span>
            </span>
            <span style={{ fontSize: "14px", fontVariantNumeric: "tabular-nums" }}>{h.amount}</span>
            <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: h.sBg, color: h.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{h.sIcon}</span>
              {h.sText}
            </span>
          </div>
        </Fragment>
      ))}
    </section>
    </>
  );
}
