// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 1056–1068, <sc-if value="{{ scr.fphotos }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrFphotosTpl({ v }: { v: any }) {
  return (
    <>
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(14px, 2cqi, 18px)", display: "flex", flexDirection: "column", gap: "12px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
        <span style={{ fontSize: "18px", fontWeight: "500" }}>Tue 20 Oct</span>
        <span style={{ fontSize: "14px", color: "#5E5852" }}>{v.fp.count}</span>
      </div>
      {(v.fp.groups || []).map((g: any, g_i: number) => (
        <Fragment key={g_i}>
          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
            <span style={{ fontSize: "13px", fontWeight: "600", color: "#3D6B4F" }}>{g.label}</span>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "6px" }}>
              {(g.photos || []).map((p: any, p_i: number) => (
                <Fragment key={p_i}>
                  <div style={{ position: "relative", aspectRatio: "1", borderRadius: "12px", background: p.bg }}>
                    <span style={{ position: "absolute", left: "6px", bottom: "6px", height: "22px", padding: "0 8px", borderRadius: "999px", background: "rgba(255,255,255,0.92)", fontSize: "12px", fontWeight: "600", display: "flex", alignItems: "center" }}>{p.time}</span>
                  </div>
                </Fragment>
              ))}
            </div>
          </div>
        </Fragment>
      ))}
    </section>
    </>
  );
}
