// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 1070–1092, <sc-if value="{{ scr.fhealth }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrFhealthTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
      <span style={{ width: "52px", height: "52px", borderRadius: "999px", background: v.fh.avBg, color: v.fh.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "18px", fontWeight: "500", flex: "none" }}>{v.fh.ini}</span>
      <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
        <span style={{ fontSize: "20px", fontWeight: "400", color: "#2B231C" }}>{v.fh.name}</span>
        <span style={{ fontSize: "13px", color: "#5E5852" }}>{v.fh.meta}</span>
      </span>
    </div>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))", gap: "8px" }}>
      {(v.fh.metrics || []).map((m: any, m_i: number) => (
        <Fragment key={m_i}>
          <div style={{ background: "#FFFFFF", border: "1px solid #E4DACD", borderRadius: "16px", padding: "12px", display: "flex", flexDirection: "column", gap: "4px", boxShadow: "0 2px 8px rgba(60,45,30,.06)" }}>
            <span style={{ fontSize: "11px", letterSpacing: "1.2px", textTransform: "uppercase", fontWeight: "600", color: "#5E5852" }}>{m.label}</span>
            <span style={{ fontSize: "24px", fontWeight: "400", letterSpacing: "-0.5px", fontVariantNumeric: "tabular-nums" }}>
              {m.value}
              <span style={{ fontSize: "12px", color: "#5E5852", marginLeft: "3px" }}>{m.unit}</span>
            </span>
            <span style={{ fontSize: "12px", color: "#5E5852" }}>{m.when}</span>
            {m.hasS ? (
              <>
                <span style={{ alignSelf: "flex-start", height: "20px", padding: "0 7px 0 5px", borderRadius: "999px", background: "#E3EFE6", color: "#2F5A40", fontSize: "11px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "13px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>check_circle</span>
                  Normal
                </span>
              </>
            ) : null}
          </div>
        </Fragment>
      ))}
    </div>
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "14px 16px", display: "flex", flexDirection: "column", gap: "10px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: "8px", flexWrap: "wrap" }}>
        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Systolic on arrival</span>
        <span style={{ fontSize: "12px", color: "#5E5852" }}>13 readings since Wed 23 Sept</span>
      </div>
      <div style={{ height: "96px", display: "flex", alignItems: "flex-end", gap: "4px", padding: "6px", borderRadius: "10px", background: "#F1F6F2" }}>
        {(v.fh.bars || []).map((b: any, b_i: number) => (
          <Fragment key={b_i}>
            <span style={{ flex: "1", height: `${b.h}%`, borderRadius: "4px", background: "#8FB39C" }} />
          </Fragment>
        ))}
      </div>
      <span style={{ fontSize: "12px", color: "#5E5852" }}>Shaded: normal range 100–139</span>
    </section>
    </>
  );
}
