// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 379–407, <sc-if value="{{ scr.family }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrFamilyTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ width: "100%", maxWidth: "680px", alignSelf: "center", display: "flex", flexDirection: "column", gap: "clamp(20px, 3cqi, 32px)" }}>
      <div role="tablist" style={{ display: "flex", gap: "28px", borderBottom: "1px solid #E6DDD1" }}>
        {(v.famTabs3 || []).map((t: any, t_i: number) => (
          <Fragment key={t_i}>
            <button role="tab" onclick={t.onClick} style={{ padding: "0 0 12px", marginBottom: "-1px", border: "none", borderBottom: `2px solid ${t.line}`, background: "transparent", fontSize: "15px", fontWeight: t.weight, color: t.color, cursor: "pointer", fontFamily: "Inter" }}>{t.label}</button>
          </Fragment>
        ))}
      </div>
      {(v.fam.cards || []).map((m: any, m_i: number) => (
        <Fragment key={m_i}>
          <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "28px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 18px 40px rgba(60,40,20,.07)", padding: "clamp(20px, 3.4cqi, 36px)", display: "flex", flexDirection: "column", gap: "26px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "18px" }}>
              <span style={{ width: "64px", height: "64px", borderRadius: "999px", background: m.avBg, color: m.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "22px", fontWeight: "500", flex: "none", boxShadow: "inset 0 0 0 3px #FFFFFF, 0 0 0 1px #D9CBB8" }}>{m.ini}</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "3px" }}>
                <span style={{ fontSize: "clamp(24px, 2.8cqi, 30px)", lineHeight: "1.1", fontWeight: "400", letterSpacing: "-0.6px", color: "#2B231C" }}>{m.name}</span>
                <span style={{ fontSize: "14px", color: "#6B6259" }}>{m.plan}</span>
              </span>
              <a href="#" style={{ fontSize: "14px", flex: "none" }}>Profile</a>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "15px" }}>
              <span style={{ width: "8px", height: "8px", borderRadius: "999px", background: "#BBA88F", flex: "none" }} />
              <span>
                <span style={{ fontWeight: "500" }}>Not at the club yet.</span>
                {' '}
                <span style={{ color: "#6B6259" }}>Usually arrives around 10:05.</span>
              </span>
            </div>
            {m.hasLog ? (
              <>
                <div style={{ display: "flex", flexDirection: "column", gap: "12px", paddingTop: "24px", borderTop: "1px solid #F0EAE1" }}>
                  <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>From the team</span>
                  <span style={{ fontSize: "clamp(21px, 2.4cqi, 26px)", lineHeight: "1.4", fontWeight: "300", letterSpacing: "-0.4px", color: "#2B231C" }}>“Oma Lina had a calm day and joined batik painting.”</span>
                  <span style={{ fontSize: "14px", color: "#6B6259" }}>Dinar · Tuesday 20 October · calm · ate all of lunch</span>
                  <div style={{ display: "flex", gap: "10px", alignItems: "center", borderBottom: "1px solid #DDD1C2", padding: "6px 0" }}>
                    <input placeholder="Reply to the team" style={{ flex: "1", minWidth: "0", border: "none", outline: "none", background: "transparent", fontSize: "16px", fontFamily: "Inter" }} />
                    <a href="#" style={{ fontSize: "14px" }}>Send</a>
                  </div>
                </div>
              </>
            ) : null}
            <div style={{ display: "flex", alignItems: "center", gap: "16px", paddingTop: "24px", borderTop: "1px solid #F0EAE1", flexWrap: "wrap" }}>
              <span style={{ flex: "1 1 200px", display: "flex", flexDirection: "column", gap: "2px" }}>
                <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>October invoice</span>
                <span style={{ fontSize: "28px", lineHeight: "1.15", fontWeight: "300", letterSpacing: "-0.6px" }}>{m.amount}</span>
                <span style={{ fontSize: "13px", color: "#6B6259" }}>Due Tuesday 27 October</span>
              </span>
              <button style={{ height: "46px", padding: "0 24px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "15px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter" }}>Pay now</button>
            </div>
          </section>
        </Fragment>
      ))}
    </div>
    </>
  );
}
