// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 962–992, <sc-if value="{{ scr.hr }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrHrTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", gap: "8px", alignItems: "center", padding: "10px 14px", borderRadius: "14px", background: "#F3EEE8", fontSize: "14px", lineHeight: "1.45" }}>
      <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1", color: "#5E4E3B" }}>lock</span>
      Management only. Contracts, salaries, bank details and disciplinary notes are hidden from every other role.
    </div>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(12px, 2cqi, 24px)", alignItems: "flex-start" }}>
      <section style={{ flex: "0 1 320px", width: "100%", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        {(v.pp.list || []).map((p: any, p_i: number) => (
          <Fragment key={p_i}>
            <button onclick={p.onClick} style={{ width: "100%", display: "flex", gap: "12px", alignItems: "center", padding: "9px 14px", minHeight: "56px", border: "none", borderTop: p.bt, borderLeft: `3px solid ${p.bar}`, background: p.bg, textAlign: "left", cursor: "pointer", fontFamily: "Inter", color: "#24201C" }}>
              <span style={{ width: "36px", height: "36px", borderRadius: "999px", background: "#EDE5DA", color: "#5E4E3B", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "13px", fontWeight: "500", flex: "none" }}>{p.ini}</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{p.name}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{p.title}</span>
              </span>
              {p.noAccess ? (
                <>
                  <span style={{ fontSize: "12px", color: "#5E5852" }}>No app</span>
                </>
              ) : null}
            </button>
          </Fragment>
        ))}
      </section>
      <div style={{ flex: "1 1 480px", minWidth: "0", display: "flex", flexDirection: "column", gap: "12px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "12px", flexWrap: "wrap" }}>
          <span style={{ width: "52px", height: "52px", borderRadius: "999px", background: "#EDE5DA", color: "#5E4E3B", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "18px", fontWeight: "500", flex: "none" }}>{v.pp.sel.ini}</span>
          <span style={{ flex: "1 1 200px", display: "flex", flexDirection: "column" }}>
            <span style={{ fontSize: "clamp(20px, 2cqi, 24px)", fontWeight: "400", color: "#2B231C" }}>{v.pp.sel.name}</span>
            <span style={{ fontSize: "14px", color: "#5E5852" }}>{v.pp.sel.title}{" · "}{v.pp.sel.phone}</span>
          </span>
          <button style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", color: "#24201C", fontSize: "14px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>edit</span>
            Edit
          </button>
        </div>
        <div role="tablist" style={{ display: "flex", gap: "4px", padding: "4px", borderRadius: "999px", background: "#EDE5DA", overflowX: "auto", scrollbarWidth: "none" }}>
          {(v.pp.tabs || []).map((t: any, t_i: number) => (
            <Fragment key={t_i}>
              <button role="tab" onclick={t.onClick} style={{ height: "36px", padding: "0 14px", borderRadius: "999px", border: "none", background: t.bg, boxShadow: t.shadow, color: "#24201C", fontSize: "14px", fontWeight: t.weight, cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>{t.label}</button>
            </Fragment>
          ))}
        </div>
        <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "4px 18px" }}>
          {(v.pp.rows || []).map((r: any, r_i: number) => (
            <Fragment key={r_i}>
              <div style={{ display: "flex", justifyContent: "space-between", gap: "12px", padding: "11px 0", borderTop: r.bt, fontSize: "15px" }}>
                <span style={{ color: "#5E5852" }}>{r.k}</span>
                <span style={{ textAlign: "right" }}>{r.v}</span>
              </div>
            </Fragment>
          ))}
        </section>
        <button onclick={v.pp.toggle} role="switch" style={{ display: "flex", alignItems: "flex-start", gap: "12px", padding: "12px 14px", borderRadius: "16px", border: "1px solid #E4DACD", background: "#FFFFFF", textAlign: "left", cursor: "pointer", fontFamily: "Inter", color: "#24201C" }}>
          <span style={{ width: "44px", height: "26px", borderRadius: "999px", background: v.pp.track, position: "relative", flex: "none", marginTop: "1px" }}>
            <span style={{ position: "absolute", top: "3px", left: `${v.pp.knob}px`, width: "20px", height: "20px", borderRadius: "999px", background: "#FFFFFF", boxShadow: "0 1px 2px rgba(0,0,0,0.2)" }} />
          </span>
          <span style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
            <span style={{ fontSize: "15px", fontWeight: "500" }}>Can sign in to the app</span>
            <span style={{ fontSize: "13px", color: "#5E5852" }}>Uses their username and password.</span>
          </span>
        </button>
      </div>
    </div>
    </>
  );
}
