// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 179–260, <sc-if value="{{ scr.health }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrHealthTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(12px, 2cqi, 24px)", alignItems: "flex-start" }}>
      <section style={{ flex: "0 1 330px", width: "100%", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "14px 16px 12px", display: "flex", flexDirection: "column", gap: "10px" }}>
          <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
            <h2 style={{ margin: "0", fontSize: "20px", fontWeight: "400", color: "#2B231C" }}>Queue</h2>
            <span style={{ fontSize: "14px", color: "#5E5852" }}>3 in the club</span>
          </div>
          <div role="tablist" style={{ display: "flex", gap: "4px", padding: "4px", borderRadius: "999px", background: "#EDE5DA" }}>
            {(v.hc.tabs || []).map((t: any, t_i: number) => (
              <Fragment key={t_i}>
                <button role="tab" onclick={t.onClick} style={{ flex: "1", height: "36px", borderRadius: "999px", border: "none", background: t.bg, boxShadow: t.shadow, color: "#24201C", fontSize: "14px", fontWeight: t.weight, cursor: "pointer", fontFamily: "Inter" }}>{t.label}</button>
              </Fragment>
            ))}
          </div>
        </div>
        {(v.hc.queue || []).map((q: any, q_i: number) => (
          <Fragment key={q_i}>
            <button onclick={q.onClick} style={{ width: "100%", display: "flex", gap: "12px", alignItems: "flex-start", padding: "12px 16px", border: "none", borderTop: "1px solid #F0EAE1", borderLeft: `3px solid ${q.bar}`, background: q.bg, textAlign: "left", cursor: "pointer", fontFamily: "Inter", color: "#24201C" }}>
              <span style={{ width: "38px", height: "38px", borderRadius: "999px", background: q.avBg, color: q.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>{q.ini}</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "3px" }}>
                <span style={{ display: "flex", justifyContent: "space-between", gap: "8px" }}>
                  <span style={{ fontSize: "15px", fontWeight: "500" }}>{q.name}</span>
                  <span style={{ fontSize: "13px", color: "#5E5852", whiteSpace: "nowrap" }}>{q.time}</span>
                </span>
                <span style={{ fontSize: "13px", color: "#5E5852", lineHeight: "1.4" }}>{q.sub}</span>
                {q.hasBadge ? (
                  <>
                    <span style={{ alignSelf: "flex-start", height: "21px", padding: "0 7px 0 5px", borderRadius: "999px", background: q.bBg, color: q.bFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px" }}>
                      <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{q.bIcon}</span>
                      {q.bText}
                    </span>
                  </>
                ) : null}
              </span>
            </button>
          </Fragment>
        ))}
        <div style={{ padding: "12px 16px 14px", borderTop: "1px solid #F0EAE1" }}>
          <button style={{ width: "100%", height: "42px", borderRadius: "999px", border: "1px solid #D9CCBC", background: "#FFFFFF", color: "#2B231C", fontSize: "14px", fontWeight: "500", display: "flex", alignItems: "center", justifyContent: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1" }}>playlist_add</span>
            Add to queue
          </button>
        </div>
      </section>
      {v.hc.hasSel ? (
        <>
          <section style={{ flex: "1 1 520px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
            <div style={{ padding: "clamp(14px, 1.8cqi, 20px)", display: "flex", gap: "14px", alignItems: "center", flexWrap: "wrap", borderBottom: "1px solid #F0EAE1" }}>
              <span style={{ width: "52px", height: "52px", borderRadius: "999px", background: v.hc.sel.avBg, color: v.hc.sel.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "18px", fontWeight: "500", flex: "none" }}>{v.hc.sel.ini}</span>
              <div style={{ flex: "1 1 200px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
                <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Arrival check</span>
                <span style={{ fontSize: "clamp(20px, 2cqi, 24px)", fontWeight: "500", color: "#24201C", letterSpacing: "-0.3px" }}>{v.hc.sel.name}</span>
                <span style={{ fontSize: "14px", color: "#5E5852" }}>{v.hc.sel.meta}</span>
              </div>
              <div style={{ display: "flex", gap: "8px" }}>
                <button style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", color: "#24201C", fontSize: "14px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>folder_open</span>
                  Record
                </button>
                <button style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", color: "#24201C", fontSize: "14px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>monitoring</span>
                  Trends
                </button>
              </div>
            </div>
            <div style={{ padding: "12px clamp(14px, 1.8cqi, 20px)", display: "flex", flexDirection: "column", gap: "6px", background: "#FBFAF8", borderBottom: "1px solid #F0EAE1" }}>
              <span style={{ fontSize: "14px", lineHeight: "1.45", color: "#24201C" }}>
                <span style={{ fontWeight: "600" }}>{"Care · "}</span>
                {v.hc.sel.care}
              </span>
              {v.hc.sel.hasNote ? (
                <>
                  <span style={{ fontSize: "14px", lineHeight: "1.45", display: "flex", gap: "6px" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "17px", lineHeight: "1.3", color: "#5E5852" }}>lock</span>
                    <span>
                      <span style={{ fontWeight: "600" }}>{"Staff only: "}</span>
                      {v.hc.sel.note}
                    </span>
                  </span>
                </>
              ) : null}
            </div>
            <div style={{ padding: "clamp(14px, 1.8cqi, 20px)", display: "flex", flexWrap: "wrap", gap: "16px", alignItems: "flex-start" }}>
              <div style={{ flex: "1 1 340px", minWidth: "0", display: "flex", flexDirection: "column", gap: "14px" }}>
                {(v.hc.blocks || []).map((b: any, b_i: number) => (
                  <Fragment key={b_i}>
                    <div style={{ border: "1px solid #E2DBD2", borderRadius: "16px", padding: "12px", display: "flex", flexDirection: "column", gap: "10px" }}>
                      <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                        <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "21px", lineHeight: "1", color: "#75624B" }}>{b.glyph}</span>
                        <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column" }}>
                          <span style={{ fontSize: "15px", fontWeight: "600" }}>{b.title}</span>
                          <span style={{ fontSize: "13px", color: "#5E5852" }}>{b.last}</span>
                        </span>
                        <button onclick={b.onRead} style={{ height: "36px", padding: "0 12px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "13px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "5px", cursor: "pointer", fontFamily: "Inter", flex: "none" }}>
                          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "17px", lineHeight: "1" }}>bluetooth</span>
                          Read PC-303
                        </button>
                      </div>
                      <div style={{ display: "flex", gap: "8px" }}>
                        {(b.fields || []).map((f: any, f_i: number) => (
                          <Fragment key={f_i}>
                            <button onclick={f.onClick} style={{ flex: "1", minWidth: "0", height: "72px", borderRadius: "12px", border: f.bd, background: "#FFFFFF", padding: "8px 10px", display: "flex", flexDirection: "column", justifyContent: "space-between", alignItems: "flex-start", cursor: "pointer", fontFamily: "Inter", color: "#24201C" }}>
                              <span style={{ fontSize: "11px", letterSpacing: "1.2px", textTransform: "uppercase", fontWeight: "600", color: "#5E5852" }}>{f.label}</span>
                              <span style={{ fontSize: "22px", fontWeight: "400", fontVariantNumeric: "tabular-nums", lineHeight: "1" }}>
                                {f.value}
                                <span style={{ fontSize: "12px", color: "#5E5852", marginLeft: "3px" }}>{f.unit}</span>
                              </span>
                            </button>
                          </Fragment>
                        ))}
                      </div>
                    </div>
                  </Fragment>
                ))}
              </div>
              <div style={{ flex: "0 1 220px", minWidth: "0", width: "100%", display: "flex", flexDirection: "column", gap: "8px" }}>
                <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>{"Keypad · "}{v.hc.activeLabel}</span>
                <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "6px" }}>
                  {(v.hc.keys || []).map((k: any, k_i: number) => (
                    <Fragment key={k_i}>
                      <button className="dh8" onclick={k.onClick} style={{ height: "50px", borderRadius: "12px", border: "none", background: "#F3EEE8", color: "#24201C", fontSize: "20px", fontFamily: "Inter", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <span style={{ fontFamily: k.font, fontSize: `${k.size}px`, lineHeight: "1" }}>{k.label}</span>
                      </button>
                    </Fragment>
                  ))}
                </div>
              </div>
            </div>
            <div style={{ padding: "12px clamp(14px, 1.8cqi, 20px) 16px", borderTop: "1px solid #F0EAE1", display: "flex", alignItems: "center", gap: "12px", flexWrap: "wrap" }}>
              <span style={{ flex: "1 1 240px", fontSize: "13px", color: "#5E5852", lineHeight: "1.4" }}>{v.hc.needed}</span>
              <button onclick={v.hc.skip} style={{ height: "42px", padding: "0 14px", border: "none", background: "transparent", color: "#75624B", fontSize: "14px", fontWeight: "500", textDecoration: "underline", textUnderlineOffset: "4px", cursor: "pointer", fontFamily: "Inter" }}>Skip for now</button>
              <button onclick={v.hc.save} style={{ height: "44px", padding: "0 20px", borderRadius: "999px", border: "none", background: v.hc.saveBg, color: v.hc.saveFg, fontSize: "15px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1" }}>check</span>
                Save and next
              </button>
            </div>
          </section>
        </>
      ) : null}
      {v.hc.noSel ? (
        <>
          <section style={{ flex: "1 1 520px", minWidth: "0", background: "#FFFFFF", border: "1px solid #E4DACD", borderRadius: "20px", padding: "40px 24px", display: "flex", flexDirection: "column", alignItems: "center", gap: "10px", textAlign: "center" }}>
            <span style={{ width: "60px", height: "60px", borderRadius: "999px", background: "#EAF1EC", color: "#3D6B4F", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "30px", lineHeight: "1" }}>task_alt</span>
            </span>
            <span style={{ fontSize: "19px", fontWeight: "500" }}>Queue is clear</span>
            <span style={{ fontSize: "14px", color: "#5E5852" }}>Everyone in the club has had their arrival check.</span>
          </section>
        </>
      ) : null}
    </div>
    </>
  );
}
