// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 706–730, <sc-if value="{{ scr.kfeed }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrKfeedTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", gap: "8px", overflowX: "auto", scrollbarWidth: "none", flex: "none" }}>
      {(v.fb.chips || []).map((c: any, c_i: number) => (
        <Fragment key={c_i}>
          <button onclick={c.onClick} style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: c.bd, background: c.bg, color: c.fg, fontSize: "14px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>
            {c.label}{" "}
            <span style={{ opacity: ".75" }}>{c.n}</span>
          </button>
        </Fragment>
      ))}
    </div>
    <div style={{ maxWidth: "780px", width: "100%", display: "flex", flexDirection: "column", gap: "12px" }}>
      {(v.fb.items || []).map((f: any, f_i: number) => (
        <Fragment key={f_i}>
          <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(14px, 1.8cqi, 18px)", display: "flex", flexDirection: "column", gap: "10px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
              <span style={{ width: "40px", height: "40px", borderRadius: "999px", background: f.avBg, color: f.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>{f.ini}</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{f.member}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{f.from}</span>
              </span>
              <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: f.sBg, color: f.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", flex: "none" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{f.sIcon}</span>
                {f.sText}
              </span>
            </div>
            <span style={{ fontSize: "13px", color: "#5E5852", display: "flex", alignItems: "center", gap: "5px" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "16px", lineHeight: "1", color: "#75624B" }}>restaurant</span>
              {f.dish}
            </span>
            <span style={{ fontSize: "16px", lineHeight: "1.5" }}>“{f.text}”</span>
            {f.answered ? (
              <>
                <div style={{ padding: "10px 14px", borderRadius: "14px", background: "#EAF1EC", display: "flex", flexDirection: "column", gap: "3px" }}>
                  <span style={{ fontSize: "15px", lineHeight: "1.45" }}>{f.reply}</span>
                  <span style={{ fontSize: "12px", color: "#2F5A40", fontWeight: "600" }}>{f.replyBy}</span>
                </div>
              </>
            ) : null}
            {f.open ? (
              <>
                <div style={{ display: "flex", gap: "8px" }}>
                  <input value={f.draft} onchange={f.onDraft} placeholder="Reply to the family" style={{ flex: "1", minWidth: "0", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", color: "#24201C", outline: "none" }} />
                  <button onclick={f.send} style={{ height: "44px", padding: "0 16px", borderRadius: "999px", border: "none", background: f.sendBg, color: f.sendFg, fontSize: "14px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter", flex: "none" }}>Send</button>
                </div>
              </>
            ) : null}
          </section>
        </Fragment>
      ))}
    </div>
    </>
  );
}
