// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 298–334, <sc-if value="{{ scr.kitchen }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrKitchenTpl({ v }: { v: any }) {
  return (
    <>
    <section style={{ background: "#FFFFFF", border: `1px solid ${v.kt.bd}`, borderRadius: "20px", boxShadow: "0 2px 8px rgba(60,45,30,.06)", overflow: "hidden" }}>
      <div style={{ padding: "14px 18px 10px", display: "flex", justifyContent: "space-between", gap: "8px", flexWrap: "wrap" }}>
        <span style={{ fontSize: "12px", letterSpacing: "1.4px", textTransform: "uppercase", fontWeight: "600", color: "#9A3D24" }}>Allergy conflicts today</span>
        <span style={{ fontSize: "13px", color: "#5E5852" }}>{v.kt.count}</span>
      </div>
      <div style={{ display: "flex", gap: "12px", alignItems: "center", padding: "12px 18px", borderTop: "1px solid #F0EAE1", flexWrap: "wrap" }}>
        <span style={{ width: "40px", height: "40px", borderRadius: "999px", background: v.kt.iconBg, color: v.kt.iconFg, display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}>
          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "21px", lineHeight: "1" }}>{v.kt.glyph}</span>
        </span>
        <span style={{ flex: "1 1 200px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
          <span style={{ fontSize: "15px", fontWeight: "500" }}>Bapak Bambang</span>
          <span style={{ fontSize: "13px", color: "#5E5852" }}>Sop ikan kakap contains fish · seafood allergy</span>
        </span>
        <span style={{ height: "24px", padding: "0 9px 0 6px", borderRadius: "999px", background: v.kt.bBg, color: v.kt.bFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "4px" }}>
          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "15px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{v.kt.bIcon}</span>
          {v.kt.bText}
        </span>
        <button onclick={v.kt.toggle} style={{ height: "40px", padding: "0 16px", borderRadius: "999px", border: "1px solid #75624B", background: v.kt.btnBg, color: v.kt.btnFg, fontSize: "14px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
          <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>{v.kt.btnIcon}</span>
          {v.kt.btn}
        </button>
      </div>
    </section>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(12px, 2cqi, 24px)", alignItems: "flex-start" }}>
      <section style={{ flex: "1 1 420px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "clamp(14px, 2cqi, 20px)", display: "flex", flexDirection: "column", gap: "8px" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Lunch 12:00 · 4 covers so far</span>
          <span style={{ fontSize: "13px", color: "#5E5852", lineHeight: "1.4" }}>3 in the club + 1 guest. Updates live as members check in.</span>
          <span style={{ fontSize: "clamp(20px, 2cqi, 24px)", lineHeight: "1.3", fontWeight: "500", letterSpacing: "-0.3px", color: "#5E4E3B", marginTop: "4px" }}>Sop ikan kakap, Nasi merah, Tumis buncis wortel, Pepaya</span>
          <span style={{ fontSize: "15px" }}>
            <span style={{ color: "#5E5852" }}>{"Soft option · "}</span>
            Bubur ikan
          </span>
          <span style={{ fontSize: "15px" }}>
            <span style={{ color: "#5E5852" }}>{"Afternoon tea 15:00 · "}</span>
            Kue lumpur, Teh melati
          </span>
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginTop: "6px" }}>
            <button style={{ height: "40px", padding: "0 14px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "14px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>add_a_photo</span>
              Add lunch photo
            </button>
            <button style={{ height: "40px", padding: "0 14px", borderRadius: "999px", border: "1px solid #D9CCBC", background: "#FFFFFF", color: "#2B231C", fontSize: "14px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>edit_calendar</span>
              Change menu
            </button>
          </div>
          <span style={{ fontSize: "13px", color: "#5E5852" }}>Families see the lunch photo on their Today page.</span>
        </div>
      </section>
      <section style={{ flex: "1 1 360px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "14px 18px 10px", display: "flex", justifyContent: "space-between" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Dietary needs today</span>
          <span style={{ fontSize: "13px", color: "#5E5852" }}>Here so far</span>
        </div>
        {(v.kt.diet || []).map((d: any, d_i: number) => (
          <Fragment key={d_i}>
            <div style={{ display: "flex", gap: "12px", alignItems: "center", padding: "9px 18px", borderTop: "1px solid #F0EAE1", minHeight: "56px" }}>
              <span style={{ width: "34px", height: "34px", borderRadius: "999px", background: d.bg, color: d.fg, display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>{d.glyph}</span>
              </span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{d.title}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{d.who}</span>
              </span>
              <span style={{ fontSize: "15px", fontWeight: "500" }}>1</span>
            </div>
          </Fragment>
        ))}
      </section>
    </div>
    </>
  );
}
