// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 733–759, <sc-if value="{{ scr.kstock }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrKstockTpl({ v }: { v: any }) {
  return (
    <>
    <section style={{ maxWidth: "900px", width: "100%", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(14px, 1.8cqi, 18px)", display: "flex", flexDirection: "column", gap: "10px" }}>
      <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>New request</span>
      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
        <input placeholder="Item" style={{ flex: "2 1 200px", minWidth: "0", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", color: "#24201C", outline: "none" }} />
        <input placeholder="Qty" inputmode="numeric" style={{ flex: "0 1 90px", minWidth: "0", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", color: "#24201C", outline: "none" }} />
        <select style={{ flex: "0 1 120px", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 10px", fontSize: "15px", fontFamily: "Inter", color: "#24201C", background: "#FFFFFF" }}>
          <option>pcs</option>
          <option>boxes</option>
          <option>packs</option>
          <option>kg</option>
          <option>litres</option>
          <option>bottles</option>
          <option>rolls</option>
          <option>sets</option>
        </select>
        <select style={{ flex: "0 1 160px", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 10px", fontSize: "15px", fontFamily: "Inter", color: "#24201C", background: "#FFFFFF" }}>
          <option>Kitchen</option>
          <option>Health</option>
          <option>Activities</option>
          <option>Housekeeping</option>
          <option>Transport</option>
        </select>
        <button style={{ flex: "0 0 auto", height: "44px", padding: "0 18px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "14px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>Send request</button>
      </div>
    </section>
    <div style={{ display: "flex", gap: "8px", overflowX: "auto", scrollbarWidth: "none", flex: "none", maxWidth: "900px" }}>
      {(v.sk.chips || []).map((c: any, c_i: number) => (
        <Fragment key={c_i}>
          <button onclick={c.onClick} style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: c.bd, background: c.bg, color: c.fg, fontSize: "14px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>
            {c.label}{" "}
            <span style={{ opacity: ".75" }}>{c.n}</span>
          </button>
        </Fragment>
      ))}
    </div>
    <section style={{ maxWidth: "900px", width: "100%", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
      {(v.sk.rows || []).map((r: any, r_i: number) => (
        <Fragment key={r_i}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px 12px", padding: "12px clamp(14px, 1.8cqi, 20px)", minHeight: "64px", borderTop: r.bt, flexWrap: "wrap" }}>
            <span style={{ flex: "1 1 240px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
              <span style={{ fontSize: "15px", fontWeight: "500" }}>{r.title}</span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{r.sub}</span>
            </span>
            <span style={{ display: "flex", alignItems: "center", gap: "8px", marginLeft: "auto" }}>
              <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: r.sBg, color: r.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", whiteSpace: "nowrap" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{r.sIcon}</span>
                {r.sText}
              </span>
              {r.canAct ? (
                <>
                  <button onclick={r.onAct} style={{ height: "36px", padding: "0 14px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "13px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>{r.act}</button>
                </>
              ) : null}
              <button className="dh18" aria-label="More" style={{ width: "34px", height: "34px", borderRadius: "999px", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#5E5852" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>more_vert</span>
              </button>
            </span>
          </div>
        </Fragment>
      ))}
    </section>
    </>
  );
}
