// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 410–430, <sc-if value="{{ scr.members }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrMembersTpl({ v }: { v: any }) {
  return (
    <>
    <label style={{ height: "46px", maxWidth: "520px", display: "flex", alignItems: "center", gap: "10px", padding: "0 14px", border: "1px solid #DDD1C2", borderRadius: "14px", background: "#FFFFFF" }}>
      <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "21px", lineHeight: "1", color: "#5E5852" }}>search</span>
      <input placeholder="Search by name, family or phone" style={{ flex: "1", minWidth: "0", border: "none", outline: "none", fontSize: "16px", fontFamily: "Inter", color: "#24201C", background: "transparent" }} />
    </label>
    <div style={{ display: "flex", gap: "8px", overflowX: "auto", scrollbarWidth: "none", flex: "none" }}>
      {(v.mem.chips || []).map((c: any, c_i: number) => (
        <Fragment key={c_i}>
          <button onclick={c.onClick} style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: c.bd, background: c.bg, color: c.fg, fontSize: "14px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>
            {c.label}{" "}
            <span style={{ opacity: ".75" }}>{c.n}</span>
          </button>
        </Fragment>
      ))}
    </div>
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
      {(v.mem.rows || []).map((r: any, r_i: number) => (
        <Fragment key={r_i}>
          <button className="dh10" style={{ width: "100%", display: "flex", alignItems: "center", gap: "12px", padding: "10px clamp(14px, 1.8cqi, 20px)", minHeight: "68px", border: "none", borderTop: r.bt, background: "#FFFFFF", textAlign: "left", cursor: "pointer", fontFamily: "Inter", color: "#24201C", flexWrap: "wrap" }}>
            <span style={{ width: "42px", height: "42px", borderRadius: "999px", background: r.avBg, color: r.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "15px", fontWeight: "500", flex: "none" }}>{r.ini}</span>
            <span style={{ flex: "1 1 200px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
              <span style={{ fontSize: "16px", fontWeight: "500" }}>{r.name}</span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{r.sub}</span>
            </span>
            <span style={{ flex: "1 1 220px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
              <span style={{ fontSize: "14px", display: "flex", alignItems: "center", gap: "7px" }}>
                <span style={{ width: "8px", height: "8px", borderRadius: "999px", background: r.dot, flex: "none" }} />
                {r.where}
              </span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{r.plan}</span>
            </span>
            <span style={{ flex: "0 0 190px", display: "flex", justifyContent: "flex-start" }}>
              {r.hasFlag ? (
                <>
                  <span style={{ height: "24px", padding: "0 9px 0 6px", borderRadius: "999px", background: r.fBg, color: r.fFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "4px", whiteSpace: "nowrap" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "15px", lineHeight: "1" }}>{r.fIcon}</span>
                    {r.flag}
                  </span>
                </>
              ) : null}
            </span>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "22px", lineHeight: "1", color: "#5E5852", flex: "none" }}>chevron_right</span>
          </button>
        </Fragment>
      ))}
      {v.mem.empty ? (
        <>
          <div style={{ padding: "28px 20px", textAlign: "center", fontSize: "15px", color: "#5E5852" }}>No members match this filter.</div>
        </>
      ) : null}
    </section>
    </>
  );
}
