// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 1022–1047, <sc-if value="{{ scr.plans }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrPlansTpl({ v }: { v: any }) {
  return (
    <>
    {v.isLaptop ? (
      <>
        <p style={{ margin: "0", fontSize: "15px", lineHeight: "1.5", maxWidth: "720px" }}>Prices tagged Sample are placeholders until the club confirms them. A new price applies from the next invoice; invoices already sent keep their amounts.</p>
      </>
    ) : null}
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "clamp(10px, 1.5cqi, 16px)" }}>
      {(v.pl.plans || []).map((p: any, p_i: number) => (
        <Fragment key={p_i}>
          <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "16px 18px", display: "flex", flexDirection: "column", gap: "10px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px" }}>
              <span style={{ fontSize: "22px", fontWeight: "400", color: "#2B231C" }}>{p.name}</span>
              <span style={{ height: "22px", padding: "0 8px", borderRadius: "999px", background: "#F6ECD6", color: "#7A5510", fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center" }}>Sample price</span>
            </div>
            <span style={{ fontSize: "14px", lineHeight: "1.45" }}>{p.desc}</span>
            <label style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
              <span style={{ fontSize: "13px", fontWeight: "600" }}>{p.per}</span>
              <span style={{ display: "flex", alignItems: "center", height: "48px", border: "1px solid #DDD1C2", borderRadius: "14px", overflow: "hidden" }}>
                <span style={{ padding: "0 12px", height: "100%", display: "flex", alignItems: "center", background: "#F6F1EA", borderRight: "1px solid #DCD3C8", fontSize: "15px" }}>Rp</span>
                <input value={p.price} onchange={p.onPrice} inputmode="numeric" style={{ flex: "1", minWidth: "0", height: "100%", border: "none", outline: "none", padding: "0 12px", fontSize: "18px", fontFamily: "Inter", color: "#24201C" }} />
              </span>
            </label>
            {(p.rows || []).map((r: any, r_i: number) => (
              <Fragment key={r_i}>
                <div style={{ display: "flex", justifyContent: "space-between", gap: "12px", paddingTop: "8px", borderTop: "1px solid #F0EAE1", fontSize: "14px" }}>
                  <span style={{ color: "#5E5852" }}>{r.k}</span>
                  <span>{r.v}</span>
                </div>
              </Fragment>
            ))}
          </section>
        </Fragment>
      ))}
    </div>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(10px, 1.5cqi, 16px)", alignItems: "flex-start" }}>
      <section style={{ flex: "0 1 320px", width: "100%", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "16px 18px", display: "flex", flexDirection: "column", gap: "8px" }}>
        <span style={{ fontSize: "20px", fontWeight: "400", color: "#2B231C" }}>Club rules</span>
        <span style={{ fontSize: "14px", lineHeight: "1.45" }}>Members come on any open day. This rule decides when a Flex visit is an extra day.</span>
        <label style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
          <span style={{ fontSize: "13px", fontWeight: "600" }}>Flex visits per month</span>
          <input value="10" inputmode="numeric" style={{ height: "46px", border: "1px solid #DDD1C2", borderRadius: "14px", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", outline: "none" }} />
        </label>
      </section>
      <section style={{ flex: "1 1 420px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "16px 18px", display: "flex", flexDirection: "column", gap: "10px" }}>
        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Next invoice preview</span>
        <div style={{ display: "flex", gap: "6px", overflowX: "auto", scrollbarWidth: "none" }}>
          {(v.pl.members || []).map((m: any, m_i: number) => (
            <Fragment key={m_i}>
              <button onclick={m.onClick} style={{ height: "36px", padding: "0 12px", borderRadius: "999px", border: m.bd, background: m.bg, color: m.fg, fontSize: "13px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>{m.label}</button>
            </Fragment>
          ))}
        </div>
        {(v.pl.lines || []).map((l: any, l_i: number) => (
          <Fragment key={l_i}>
            <div style={{ display: "flex", justifyContent: "space-between", gap: "12px", padding: "8px 0", borderTop: "1px solid #F0EAE1", fontSize: "15px" }}>
              <span>{l.k}</span>
              <span style={{ fontVariantNumeric: "tabular-nums" }}>{l.v}</span>
            </div>
          </Fragment>
        ))}
        <div style={{ display: "flex", justifyContent: "space-between", gap: "12px", paddingTop: "10px", borderTop: "2px solid #24201C", fontSize: "16px", fontWeight: "600" }}>
          <span>Total · November 2026</span>
          <span style={{ fontVariantNumeric: "tabular-nums" }}>{v.pl.total}</span>
        </div>
      </section>
    </div>
    </>
  );
}
