// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 1125–1131, <sc-if value="{{ scr.placeholder }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrPlaceholderTpl({ v }: { v: any }) {
  return (
    <>
    <section style={{ background: "#FFFFFF", border: "1px dashed #CAB8A2", borderRadius: "20px", padding: "40px 24px", display: "flex", flexDirection: "column", alignItems: "center", gap: "10px", textAlign: "center" }}>
      <span style={{ width: "60px", height: "60px", borderRadius: "999px", background: "#F3EEE8", color: "#75624B", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "30px", lineHeight: "1" }}>{v.head.glyph}</span>
      </span>
      <span style={{ fontSize: "19px", fontWeight: "500" }}>Not redesigned yet</span>
      <span style={{ fontSize: "14px", color: "#5E5852", maxWidth: "360px", lineHeight: "1.5" }}>{v.head.title}{" comes in a later pass. This round covers each role's first screen."}</span>
    </section>
    </>
  );
}
