// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 762–799, <sc-if value="{{ scr.pay }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrPayTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "clamp(8px, 1.2cqi, 14px)" }}>
      {(v.py.tiles || []).map((t: any, t_i: number) => (
        <Fragment key={t_i}>
          <div style={{ background: "#FFFFFF", border: "1px solid #E4DACD", borderRadius: "16px", padding: "12px 14px", display: "flex", flexDirection: "column", gap: "4px", boxShadow: "0 2px 8px rgba(60,45,30,.06)" }}>
            <span style={{ fontSize: "13px", fontWeight: "500", color: "#5E5852" }}>{t.label}</span>
            <span style={{ fontSize: "clamp(24px, 2.6cqi, 32px)", fontWeight: "300", lineHeight: "1.1", fontVariantNumeric: "tabular-nums" }}>{t.n}</span>
            <span style={{ fontSize: "13px", color: "#5E5852" }}>{t.sub}</span>
          </div>
        </Fragment>
      ))}
    </div>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(12px, 2cqi, 24px)", alignItems: "flex-start" }}>
      <section style={{ flex: "1 1 480px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "14px 18px 10px", display: "flex", justifyContent: "space-between", gap: "8px" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Payments as they arrive</span>
          <span style={{ fontSize: "13px", color: "#5E5852" }}>Newest first</span>
        </div>
        {(v.py.rows || []).map((r: any, r_i: number) => (
          <Fragment key={r_i}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px 12px", padding: "10px 18px", borderTop: "1px solid #F0EAE1", minHeight: "62px", flexWrap: "wrap" }}>
              <span style={{ flex: "1 1 220px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{r.name}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{r.sub}</span>
              </span>
              <span style={{ display: "flex", alignItems: "center", gap: "10px", marginLeft: "auto" }}>
                <span style={{ display: "flex", flexDirection: "column", alignItems: "flex-end" }}>
                  <span style={{ fontSize: "15px", fontWeight: "500", fontVariantNumeric: "tabular-nums" }}>{r.amount}</span>
                  <span style={{ fontSize: "12px", color: "#5E5852" }}>{r.when}</span>
                </span>
                <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: "#E3EFE6", color: "#2F5A40", fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", whiteSpace: "nowrap" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>check_circle</span>
                  Xero
                </span>
                <button aria-label="More" style={{ width: "32px", height: "32px", borderRadius: "999px", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#5E5852" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>more_vert</span>
                </button>
              </span>
            </div>
          </Fragment>
        ))}
      </section>
      <section style={{ flex: "0 1 400px", width: "100%", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "16px 18px", display: "flex", flexDirection: "column", gap: "12px" }}>
        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Manual payment</span>
        <span style={{ fontSize: "13px", color: "#5E5852", lineHeight: "1.45" }}>For families who pay from Singapore, by Revolut or in cash instead of the virtual account.</span>
        <span style={{ fontSize: "14px", fontWeight: "600" }}>Invoice</span>
        <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
          {(v.py.invs || []).map((i: any, i_i: number) => (
            <Fragment key={i_i}>
              <button onclick={i.onClick} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px", height: "42px", padding: "0 14px", borderRadius: "12px", border: i.bd, background: i.bg, color: "#24201C", fontSize: "14px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter" }}>
                <span>{i.label}</span>
                <span style={{ fontVariantNumeric: "tabular-nums", color: "#5E5852" }}>{i.amount}</span>
              </button>
            </Fragment>
          ))}
        </div>
        <span style={{ fontSize: "14px", fontWeight: "600" }}>Paid by</span>
        <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
          {(v.py.methods || []).map((m: any, m_i: number) => (
            <Fragment key={m_i}>
              <button onclick={m.onClick} style={{ height: "36px", padding: "0 12px", borderRadius: "999px", border: m.bd, background: m.bg, color: m.fg, fontSize: "13px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter" }}>{m.label}</button>
            </Fragment>
          ))}
        </div>
        <label style={{ display: "flex", alignItems: "center", height: "44px", border: "1px solid #DDD1C2", borderRadius: "14px", overflow: "hidden" }}>
          <span style={{ padding: "0 12px", height: "100%", display: "flex", alignItems: "center", background: "#F6F1EA", borderRight: "1px solid #DCD3C8", fontSize: "15px" }}>Rp</span>
          <input inputmode="numeric" placeholder="Amount credited" style={{ flex: "1", minWidth: "0", height: "100%", border: "none", outline: "none", padding: "0 12px", fontSize: "16px", fontFamily: "Inter" }} />
        </label>
        <button style={{ height: "44px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "14px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>Record payment</button>
      </section>
    </div>
    </>
  );
}
