// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 836–867, <sc-if value="{{ scr.rcpt }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrRcptTpl({ v }: { v: any }) {
  return (
    <>
    <label style={{ height: "46px", maxWidth: "520px", display: "flex", alignItems: "center", gap: "10px", padding: "0 14px", border: "1px solid #DDD1C2", borderRadius: "14px", background: "#FFFFFF" }}>
      <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "21px", lineHeight: "1", color: "#5E5852" }}>search</span>
      <input placeholder="Search receipts and vendor invoices" style={{ flex: "1", minWidth: "0", border: "none", outline: "none", fontSize: "16px", fontFamily: "Inter", color: "#24201C", background: "transparent" }} />
    </label>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(12px, 2cqi, 24px)", alignItems: "flex-start" }}>
      <section style={{ flex: "1 1 420px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "14px 18px 10px", display: "flex", justifyContent: "space-between", gap: "8px", flexWrap: "wrap" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Receipts</span>
          <span style={{ fontSize: "13px", color: "#5E5852" }}>Counted against each section's budget</span>
        </div>
        {(v.rc.receipts || []).map((r: any, r_i: number) => (
          <Fragment key={r_i}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "10px 18px", borderTop: "1px solid #F0EAE1", minHeight: "64px" }}>
              <span style={{ width: "40px", height: "48px", borderRadius: "8px", background: "radial-gradient(120% 95% at 28% 22%, #FBF6F0 0%, #E8E1D8 50%, #C9B49C 100%)", flex: "none" }} />
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{r.vendor}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{r.sub}</span>
              </span>
              <span style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: "3px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" }}>{r.amount}</span>
                <span style={{ height: "20px", padding: "0 7px 0 5px", borderRadius: "999px", background: "#E3EFE6", color: "#2F5A40", fontSize: "11px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "13px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>check_circle</span>
                  In Xero
                </span>
              </span>
              <button aria-label="More" style={{ width: "32px", height: "32px", borderRadius: "999px", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#5E5852" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>more_vert</span>
              </button>
            </div>
          </Fragment>
        ))}
      </section>
      <section style={{ flex: "1 1 420px", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "10px 12px 10px 18px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Vendor invoices</span>
          <button style={{ height: "34px", padding: "0 12px", borderRadius: "999px", border: "1px solid #D9CCBC", background: "#FFFFFF", color: "#2B231C", fontSize: "13px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "4px", cursor: "pointer", fontFamily: "Inter" }}>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "17px", lineHeight: "1" }}>add</span>
            Add
          </button>
        </div>
        {(v.rc.vendors || []).map((v: any, v_i: number) => (
          <Fragment key={v_i}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px 12px", padding: "12px 18px", borderTop: "1px solid #F0EAE1", flexWrap: "wrap" }}>
              <span style={{ flex: "1 1 200px", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{v.title}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{v.sub}</span>
              </span>
              <span style={{ display: "flex", alignItems: "center", gap: "8px", marginLeft: "auto" }}>
                <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: v.sBg, color: v.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", whiteSpace: "nowrap" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{v.sIcon}</span>
                  {v.sText}
                </span>
                {v.hasAct ? (
                  <>
                    <button onclick={v.onAct} style={{ height: "36px", padding: "0 14px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "13px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter", whiteSpace: "nowrap" }}>{v.act}</button>
                  </>
                ) : null}
                <button aria-label="More" style={{ width: "32px", height: "32px", borderRadius: "999px", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#5E5852" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>more_vert</span>
                </button>
              </span>
            </div>
          </Fragment>
        ))}
      </section>
    </div>
    </>
  );
}
