// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 870–897, <sc-if value="{{ scr.reviews }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrReviewsTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", gap: "8px", overflowX: "auto", scrollbarWidth: "none", flex: "none" }}>
      {(v.rv.chips || []).map((c: any, c_i: number) => (
        <Fragment key={c_i}>
          <button onclick={c.onClick} style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: c.bd, background: c.bg, color: c.fg, fontSize: "14px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", flex: "none", fontFamily: "Inter" }}>
            {c.label}{" "}
            <span style={{ opacity: ".75" }}>{c.n}</span>
          </button>
        </Fragment>
      ))}
    </div>
    <div style={{ maxWidth: "820px", width: "100%", display: "flex", flexDirection: "column", gap: "12px" }}>
      {(v.rv.items || []).map((r: any, r_i: number) => (
        <Fragment key={r_i}>
          <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(14px, 1.8cqi, 18px)", display: "flex", flexDirection: "column", gap: "12px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
              <span style={{ width: "40px", height: "40px", borderRadius: "999px", background: "#F1E7DC", color: "#75624B", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>BP</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                <span style={{ fontSize: "15px", fontWeight: "600" }}>Bapak Bambang Purnomo</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>Details · Caca · Lobby · Today 09:05</span>
              </span>
              <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: r.sBg, color: r.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", flex: "none" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{r.sIcon}</span>
                {r.sText}
              </span>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "4px", padding: "12px 14px", borderRadius: "14px", border: "1px solid #F0EAE1" }}>
              <span style={{ fontSize: "12px", letterSpacing: "1.3px", textTransform: "uppercase", fontWeight: "600", color: "#5E5852" }}>Usual arrival time</span>
              <span style={{ fontSize: "16px", display: "flex", alignItems: "center", gap: "8px" }}>
                <span style={{ textDecoration: "line-through", color: "#5E5852" }}>09:48</span>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1", color: "#75624B" }}>arrow_forward</span>
                <span style={{ fontWeight: "600" }}>09:30</span>
              </span>
            </div>
            <span style={{ fontSize: "14px", color: "#24201C", lineHeight: "1.45", display: "flex", gap: "6px" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1.1", color: "#75624B" }}>format_quote</span>
              Caca: Laras says Papa will come earlier from next week.
            </span>
            {r.pending ? (
              <>
                <div style={{ display: "flex", gap: "8px" }}>
                  <button onclick={v.rv.approve} style={{ height: "42px", padding: "0 18px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "14px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "19px", lineHeight: "1" }}>check</span>
                    Approve
                  </button>
                  <button onclick={v.rv.reject} style={{ height: "42px", padding: "0 16px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", color: "#9A3D24", fontSize: "14px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter" }}>Reject</button>
                </div>
              </>
            ) : null}
          </section>
        </Fragment>
      ))}
      {v.rv.empty ? (
        <>
          <section style={{ background: "#FFFFFF", border: "1px solid #E4DACD", borderRadius: "20px", padding: "36px 24px", display: "flex", flexDirection: "column", alignItems: "center", gap: "8px", textAlign: "center" }}>
            <span style={{ width: "56px", height: "56px", borderRadius: "999px", background: "#EAF1EC", color: "#3D6B4F", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "28px", lineHeight: "1" }}>task_alt</span>
            </span>
            <span style={{ fontSize: "17px", fontWeight: "500" }}>Nothing here</span>
            <span style={{ fontSize: "14px", color: "#5E5852" }}>Changes other staff make to customer details show here.</span>
          </section>
        </>
      ) : null}
    </div>
    </>
  );
}
