// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 555–591, <sc-if value="{{ scr.readings }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrReadingsTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "flex", flexWrap: "wrap", gap: "clamp(12px, 2cqi, 24px)", alignItems: "flex-start" }}>
      <section style={{ flex: "0 1 320px", width: "100%", minWidth: "0", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
        <div style={{ padding: "12px 14px", display: "flex", gap: "6px" }}>
          {(v.rd.chips || []).map((c: any, c_i: number) => (
            <Fragment key={c_i}>
              <button onclick={c.onClick} style={{ height: "34px", padding: "0 12px", borderRadius: "999px", border: c.bd, background: c.bg, color: c.fg, fontSize: "13px", fontWeight: "500", cursor: "pointer", whiteSpace: "nowrap", fontFamily: "Inter" }}>
                {c.label}{" "}
                <span style={{ opacity: ".75" }}>{c.n}</span>
              </button>
            </Fragment>
          ))}
        </div>
        {(v.rd.list || []).map((m: any, m_i: number) => (
          <Fragment key={m_i}>
            <button onclick={m.onClick} style={{ width: "100%", display: "flex", gap: "12px", alignItems: "center", padding: "10px 14px", minHeight: "62px", border: "none", borderTop: "1px solid #F0EAE1", borderLeft: `3px solid ${m.bar}`, background: m.bg, textAlign: "left", cursor: "pointer", fontFamily: "Inter", color: "#24201C" }}>
              <span style={{ width: "38px", height: "38px", borderRadius: "999px", background: m.avBg, color: m.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>{m.ini}</span>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{m.name}</span>
                <span style={{ fontSize: "13px", color: "#5E5852" }}>{m.last}</span>
              </span>
              <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: m.sBg, color: m.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", flex: "none" }}>
                <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{m.sIcon}</span>
                {m.sText}
              </span>
            </button>
          </Fragment>
        ))}
      </section>
      <div style={{ flex: "1 1 520px", minWidth: "0", display: "flex", flexDirection: "column", gap: "14px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "12px", flexWrap: "wrap" }}>
          <span style={{ width: "48px", height: "48px", borderRadius: "999px", background: v.rd.sel.avBg, color: v.rd.sel.avFg, display: "flex", alignItems: "center", justifyContent: "center", fontSize: "17px", fontWeight: "500", flex: "none" }}>{v.rd.sel.ini}</span>
          <span style={{ flex: "1 1 200px", display: "flex", flexDirection: "column" }}>
            <span style={{ fontSize: "clamp(20px, 2cqi, 24px)", fontWeight: "400", color: "#2B231C" }}>{v.rd.sel.name}</span>
            <span style={{ fontSize: "14px", color: "#5E5852" }}>{v.rd.sel.meta}{" · last 4 weeks"}</span>
          </span>
          <button style={{ height: "38px", padding: "0 14px", borderRadius: "999px", border: "1px solid #E4DACD", background: "#FFFFFF", color: "#24201C", fontSize: "14px", fontWeight: "500", display: "inline-flex", alignItems: "center", gap: "6px", cursor: "pointer", fontFamily: "Inter" }}>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "18px", lineHeight: "1" }}>folder_open</span>
            Health record
          </button>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "12px" }}>
          {(v.rd.metrics || []).map((x: any, x_i: number) => (
            <Fragment key={x_i}>
              <div style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "14px 16px", display: "flex", flexDirection: "column", gap: "8px" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "8px" }}>
                  <span style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
                    <span style={{ fontSize: "12px", letterSpacing: "1.3px", textTransform: "uppercase", fontWeight: "600", color: "#5E5852" }}>{x.label}</span>
                    <span style={{ fontSize: "26px", fontWeight: "400", letterSpacing: "-0.5px", fontVariantNumeric: "tabular-nums" }}>{x.value}</span>
                  </span>
                  <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: x.sBg, color: x.sFg, fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", flex: "none" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>{x.sIcon}</span>
                    {x.sText}
                  </span>
                </div>
                <div style={{ height: "48px", display: "flex", alignItems: "flex-end", gap: "3px", padding: "4px", borderRadius: "8px", background: "#F1F6F2" }}>
                  {(x.bars || []).map((b: any, b_i: number) => (
                    <Fragment key={b_i}>
                      <span style={{ flex: "1", height: `${b.h}%`, borderRadius: "3px", background: b.c }} />
                    </Fragment>
                  ))}
                </div>
                <span style={{ fontSize: "12px", color: "#5E5852", lineHeight: "1.4" }}>{x.note}</span>
              </div>
            </Fragment>
          ))}
        </div>
      </div>
    </div>
    </>
  );
}
