// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 526–552, <sc-if value="{{ scr.requests }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrRequestsTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "12px", maxWidth: "900px" }}>
      {(v.rq.kinds || []).map((k: any, k_i: number) => (
        <Fragment key={k_i}>
          <button className="dh16" onclick={k.onClick} style={{ display: "flex", gap: "12px", alignItems: "center", padding: "14px 16px", borderRadius: "18px", border: "1px solid #E4DACD", background: "#FFFFFF", textAlign: "left", cursor: "pointer", fontFamily: "Inter", color: "#24201C", boxShadow: "0 2px 8px rgba(60,45,30,.06)" }}>
            <span style={{ width: "42px", height: "42px", borderRadius: "12px", background: "#EAF1EC", color: "#3D6B4F", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "22px", lineHeight: "1" }}>{k.icon}</span>
            </span>
            <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "2px" }}>
              <span style={{ fontSize: "15px", fontWeight: "600" }}>{k.title}</span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{k.sub}</span>
            </span>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1", color: "#75624B" }}>add</span>
          </button>
        </Fragment>
      ))}
    </div>
    <section style={{ background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden", maxWidth: "900px" }}>
      <div style={{ padding: "14px 18px 10px", fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>My requests</div>
      {(v.rq.mine || []).map((r: any, r_i: number) => (
        <Fragment key={r_i}>
          <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "10px 18px", borderTop: "1px solid #F0EAE1", minHeight: "60px" }}>
            <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "21px", lineHeight: "1", color: "#75624B" }}>{r.icon}</span>
            <span style={{ flex: "1", display: "flex", flexDirection: "column", gap: "1px" }}>
              <span style={{ fontSize: "15px", fontWeight: "500" }}>{r.title}</span>
              <span style={{ fontSize: "13px", color: "#5E5852" }}>{r.sub}</span>
            </span>
            <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: "#F6ECD6", color: "#7A5510", fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1" }}>schedule</span>
              Requested
            </span>
          </div>
        </Fragment>
      ))}
      {v.rq.empty ? (
        <>
          <div style={{ padding: "28px 20px 34px", borderTop: "1px solid #F0EAE1", display: "flex", flexDirection: "column", alignItems: "center", gap: "8px", textAlign: "center" }}>
            <span style={{ width: "56px", height: "56px", borderRadius: "999px", background: "#F3EEE8", color: "#75624B", display: "flex", alignItems: "center", justifyContent: "center" }}>
              <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "28px", lineHeight: "1" }}>inbox</span>
            </span>
            <span style={{ fontSize: "17px", fontWeight: "500" }}>No requests yet</span>
            <span style={{ fontSize: "14px", color: "#5E5852" }}>Requests you send show here with their status.</span>
          </div>
        </>
      ) : null}
    </section>
    </>
  );
}
