// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 995–1019, <sc-if value="{{ scr.surveys }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrSurveysTpl({ v }: { v: any }) {
  return (
    <>
    <section style={{ maxWidth: "1000px", width: "100%", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", padding: "clamp(14px, 2cqi, 22px)", display: "flex", flexDirection: "column", gap: "16px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: "10px", flexWrap: "wrap", alignItems: "flex-start" }}>
        <span style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
          <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Live · sent Mon 19 Oct</span>
          <span style={{ fontSize: "22px", fontWeight: "400", color: "#2B231C" }}>October check-in</span>
        </span>
        <span style={{ height: "26px", padding: "0 10px", borderRadius: "999px", background: "#E3EFE6", color: "#2F5A40", fontSize: "13px", fontWeight: "600", display: "inline-flex", alignItems: "center" }}>3 of 4 families</span>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: "10px" }}>
        {(v.sv.stats || []).map((s: any, s_i: number) => (
          <Fragment key={s_i}>
            <div style={{ borderRadius: "16px", background: "#F6F1EA", padding: "12px 14px", display: "flex", flexDirection: "column", gap: "2px" }}>
              <span style={{ fontSize: "13px", fontWeight: "500", color: "#5E5852" }}>{s.label}</span>
              <span style={{ fontSize: "28px", fontWeight: "300", letterSpacing: "-0.5px" }}>{s.value}</span>
              <span style={{ fontSize: "12px", color: "#5E5852" }}>{s.sub}</span>
            </div>
          </Fragment>
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column" }}>
        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43", paddingBottom: "6px" }}>Team ratings</span>
        {(v.sv.team || []).map((t: any, t_i: number) => (
          <Fragment key={t_i}>
            <div style={{ display: "flex", alignItems: "center", gap: "12px", padding: "9px 0", borderTop: "1px solid #F0EAE1" }}>
              <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column" }}>
                <span style={{ fontSize: "15px", fontWeight: "500" }}>{t.name}</span>
                <span style={{ fontSize: "12px", color: "#5E5852" }}>{t.role}{" · 3 ratings"}</span>
              </span>
              <span style={{ width: "clamp(80px, 14cqi, 160px)", height: "8px", borderRadius: "999px", background: "#F0EAE1", overflow: "hidden" }}>
                <span style={{ display: "block", height: "100%", width: `${t.pct}%`, background: "#3D6B4F" }} />
              </span>
              <span style={{ width: "52px", textAlign: "right", fontSize: "14px", fontWeight: "600", fontVariantNumeric: "tabular-nums" }}>{t.score}</span>
            </div>
          </Fragment>
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
        <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>Comments</span>
        {(v.sv.comments || []).map((c: any, c_i: number) => (
          <Fragment key={c_i}>
            <div style={{ padding: "10px 14px", borderRadius: "14px", background: "#F6F1EA", display: "flex", flexDirection: "column", gap: "3px" }}>
              <span style={{ fontSize: "15px" }}>“{c.text}”</span>
              <span style={{ fontSize: "12px", color: "#5E5852" }}>{c.by}</span>
            </div>
          </Fragment>
        ))}
      </div>
    </section>
    </>
  );
}
