// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 937–959, <sc-if value="{{ scr.venue }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ScrVenueTpl({ v }: { v: any }) {
  return (
    <>
    {(v.vn.groups || []).map((g: any, g_i: number) => (
      <Fragment key={g_i}>
        <section style={{ maxWidth: "900px", width: "100%", background: "#FFFFFF", border: "1px solid #EFE7DC", borderRadius: "24px", boxShadow: "0 1px 2px rgba(60,40,20,.04), 0 14px 34px rgba(60,40,20,.06)", overflow: "hidden" }}>
          <div style={{ padding: "14px 18px 10px", display: "flex", justifyContent: "space-between", gap: "8px", flexWrap: "wrap" }}>
            <span style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase", fontWeight: "500", color: "#6E5A43" }}>{g.title}</span>
            <span style={{ fontSize: "13px", color: "#5E5852" }}>{g.meta}</span>
          </div>
          {(g.rows || []).map((b: any, b_i: number) => (
            <Fragment key={b_i}>
              <div style={{ display: "flex", gap: "12px", padding: "14px 18px", borderTop: "1px solid #F0EAE1", flexWrap: "wrap", alignItems: "flex-start" }}>
                <span style={{ width: "40px", height: "40px", borderRadius: "12px", background: "#F3EEE8", color: "#75624B", display: "flex", alignItems: "center", justifyContent: "center", flex: "none" }}>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>storefront</span>
                </span>
                <span style={{ flex: "1 1 280px", minWidth: "0", display: "flex", flexDirection: "column", gap: "3px" }}>
                  <span style={{ fontSize: "15px", fontWeight: "600" }}>{b.title}</span>
                  <span style={{ fontSize: "14px" }}>{b.when}</span>
                  <span style={{ fontSize: "13px", color: "#5E5852" }}>{b.who}{" · Rp 3.500.000 · deposit Rp 1.000.000"}</span>
                  {b.hasQuote ? (
                    <>
                      <span style={{ fontSize: "14px", lineHeight: "1.45", marginTop: "4px" }}>“{b.quote}”</span>
                    </>
                  ) : null}
                </span>
                <span style={{ display: "flex", alignItems: "center", gap: "8px", marginLeft: "auto" }}>
                  <span style={{ height: "22px", padding: "0 8px 0 6px", borderRadius: "999px", background: "#E3EFE6", color: "#2F5A40", fontSize: "12px", fontWeight: "600", display: "inline-flex", alignItems: "center", gap: "3px", whiteSpace: "nowrap" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "14px", lineHeight: "1", fontVariationSettings: "'FILL' 1" }}>check_circle</span>
                    {b.status}
                  </span>
                  <button style={{ height: "36px", padding: "0 14px", borderRadius: "999px", border: "1px solid #D9CCBC", background: "#FFFFFF", color: "#2B231C", fontSize: "13px", fontWeight: "500", cursor: "pointer", fontFamily: "Inter", whiteSpace: "nowrap" }}>Create invoice</button>
                  <button aria-label="More" style={{ width: "32px", height: "32px", borderRadius: "999px", border: "none", background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#5E5852" }}>
                    <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "20px", lineHeight: "1" }}>more_vert</span>
                  </button>
                </span>
              </div>
            </Fragment>
          ))}
        </section>
      </Fragment>
    ))}
    </>
  );
}
