// AUTO-GENERATED by scripts/dc2jsx.mjs from design/CitraPremier App.dc.html (lines 29–68, <sc-if value="{{ showLogin }}">).
// Reference markup with the design's exact styles. `v` is the prototype's renderVals() object.
/* eslint-disable */
// @ts-nocheck
import { Fragment } from 'react';

export function ShowLoginTpl({ v }: { v: any }) {
  return (
    <>
    <div style={{ flex: "1", minHeight: "0", display: "flex", background: "#F6F1EA", containerType: "inline-size" }}>
      {v.isLaptop ? (
        <>
          <div style={{ flex: "1 1 55%", minWidth: "0", display: "flex", flexDirection: "column", gap: "24px", padding: "44px", background: "#FFFFFF", borderRight: "1px solid #E2DBD2" }}>
            <img src="assets/logo-cp.jpg" alt="CitraPremier by Living Well Seniors Communities" style={{ height: "56px", width: "auto", alignSelf: "flex-start", mixBlendMode: "multiply" }} />
            <div role="img" aria-label="A member and her daughter, smiling together" style={{ flex: "1", minHeight: "160px", borderRadius: "24px", background: "30% 35% / cover no-repeat url('assets/login-family.jpg'), #E9E3DB" }} />
            <div style={{ display: "flex", flexDirection: "column", gap: "10px", maxWidth: "620px" }}>
              <div style={{ fontSize: "13px", letterSpacing: "1.5px", textTransform: "uppercase", fontWeight: "600", color: "#3D6B4F" }}>More hospitality, less hospital</div>
              <div style={{ fontSize: "38px", lineHeight: "46px", fontWeight: "500", letterSpacing: "-0.8px", color: "#5E4E3B", textWrap: "pretty" }}>Adding years to life, and life to years.</div>
            </div>
            <div style={{ fontSize: "14px", color: "#5E5852", lineHeight: "1.4" }}>A Living Well Seniors Communities clubhouse · open Monday to Friday, 08:30–16:30</div>
          </div>
        </>
      ) : null}
      <div style={{ flex: "1 1 auto", maxWidth: "560px", minWidth: "0", overflowY: "auto", display: "flex", flexDirection: "column", gap: "24px", padding: "clamp(20px, 6cqi, 48px)" }}>
        {v.isPhone ? (
          <>
            <img src="assets/logo-cp.jpg" alt="CitraPremier" style={{ height: "40px", width: "auto", alignSelf: "flex-start", mixBlendMode: "multiply" }} />
          </>
        ) : null}
        <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
          <h1 style={{ margin: "0", fontSize: "36px", lineHeight: "44px", fontWeight: "500", letterSpacing: "-0.8px", color: "#5E4E3B" }}>Welcome</h1>
          <p style={{ margin: "0", fontSize: "16px", lineHeight: "24px", color: "#24201C", textWrap: "pretty" }}>One sign-in for the club team and for families. Use your username and password.</p>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
          <label style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
            <span style={{ fontSize: "14px", fontWeight: "600" }}>Username</span>
            <input autocomplete="username" style={{ height: "52px", border: "1px solid #DDD1C2", borderRadius: "14px", background: "#FFFFFF", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", color: "#24201C", outline: "none" }} />
          </label>
          <label style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
            <span style={{ fontSize: "14px", fontWeight: "600" }}>Password</span>
            <input type="password" autocomplete="current-password" style={{ height: "52px", border: "1px solid #DDD1C2", borderRadius: "14px", background: "#FFFFFF", padding: "0 14px", fontSize: "16px", fontFamily: "Inter", color: "#24201C", outline: "none" }} />
          </label>
          <button className="dh3" onclick={v.signInDefault} style={{ height: "52px", borderRadius: "999px", border: "none", background: "#2B231C", color: "#F7F3EE", fontSize: "16px", fontWeight: "600", cursor: "pointer", fontFamily: "Inter" }}>Sign in</button>
          <div style={{ display: "flex", flexDirection: "column", gap: "4px", fontSize: "14px", color: "#5E5852", lineHeight: "1.4" }}>
            <span>Forgot your password? Ask the club manager to reset it.</span>
            <span>Demo: your username is your first name in lowercase, and the password is citra123.</span>
          </div>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
            <span style={{ fontSize: "13px", letterSpacing: "1.5px", textTransform: "uppercase", fontWeight: "600", color: "#3D6B4F", whiteSpace: "nowrap" }}>Demo accounts</span>
            <span style={{ flex: "1", height: "1px", background: "#E2DBD2" }} />
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
            {(v.accounts || []).map((a: any, a_i: number) => (
              <Fragment key={a_i}>
                <button className="dh4" onclick={a.onClick} style={{ display: "flex", alignItems: "center", gap: "12px", padding: "9px 14px", minHeight: "60px", borderRadius: "16px", border: "1px solid #E4DACD", background: "#FFFFFF", textAlign: "left", cursor: "pointer", color: "#24201C", fontFamily: "Inter" }}>
                  <span style={{ width: "40px", height: "40px", borderRadius: "999px", background: "#EDE5DA", color: "#5E4E3B", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "14px", fontWeight: "500", flex: "none" }}>{a.ini}</span>
                  <span style={{ flex: "1", minWidth: "0", display: "flex", flexDirection: "column", gap: "1px" }}>
                    <span style={{ fontSize: "15px", fontWeight: "500" }}>{a.name}</span>
                    <span style={{ fontSize: "13px", color: "#5E5852" }}>{a.sub}</span>
                  </span>
                  <span style={{ fontFamily: "'Material Symbols Rounded'", fontSize: "22px", lineHeight: "1", color: "#75624B" }}>arrow_forward</span>
                </button>
              </Fragment>
            ))}
          </div>
        </div>
      </div>
    </div>
    </>
  );
}
